_uniform = [
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP ACR ==================================================
			"CUP_U_B_CZ_DST_NoKneepads",
			"CUP_U_B_CZ_DST_Kneepads_Sleeve",
			"CUP_U_B_CZ_WDL_NoKneepads",
			"CUP_U_B_CZ_WDL_Kneepads_Gloves",
		// CUP BAF ==================================================
			// Комплекты BAF удалены за наличие шевронов с британским флагом
		// CUP BDU ==================================================
			"CUP_U_B_BDUv2_Alpenflage",
			"CUP_U_B_BDUv2_gloves_Alpenflage",
			"CUP_U_B_BDUv2_roll_Alpenflage",
			"CUP_U_B_BDUv2_roll_gloves_Alpenflage",
			"CUP_U_B_BDUv2_CEU",
			"CUP_U_B_BDUv2_gloves_CEU",
			"CUP_U_B_BDUv2_roll_CEU",
			"CUP_U_B_BDUv2_roll_gloves_CEU",
			"CUP_U_B_BDUv2_DCU",
			"CUP_U_B_BDUv2_gloves_DCU",
			"CUP_U_B_BDUv2_roll_DCU",
			"CUP_U_B_BDUv2_roll_gloves_DCU",
			"CUP_U_B_BDUv2_DDPM",
			"CUP_U_B_BDUv2_gloves_DDPM",
			"CUP_U_B_BDUv2_roll_DDPM",
			"CUP_U_B_BDUv2_roll_gloves_DDPM",
			"CUP_U_B_BDUv2_desert",
			"CUP_U_B_BDUv2_gloves_desert",
			"CUP_U_B_BDUv2_roll_desert",
			"CUP_U_B_BDUv2_roll_gloves_desert",
			"CUP_U_B_BDUv2_DPM",
			"CUP_U_B_BDUv2_gloves_DPM",
			"CUP_U_B_BDUv2_roll_DPM",
			"CUP_U_B_BDUv2_roll_gloves_DPM",
			"CUP_U_B_BDUv2_ERDL_highland",
			"CUP_U_B_BDUv2_gloves_ERDL_highland",
			"CUP_U_B_BDUv2_roll_ERDL_highland",
			"CUP_U_B_BDUv2_roll_gloves_ERDL_highland",
			"CUP_U_B_BDUv2_ERDL_lowland",
			"CUP_U_B_BDUv2_gloves_ERDL_lowland",
			"CUP_U_B_BDUv2_roll_ERDL_lowland",
			"CUP_U_B_BDUv2_roll_gloves_ERDL_lowland",
			"CUP_U_B_BDUv2_M81",
			"CUP_U_B_BDUv2_gloves_M81",
			"CUP_U_B_BDUv2_roll_M81",
			"CUP_U_B_BDUv2_roll_gloves_M81",
			"CUP_U_B_BDUv2_OD",
			"CUP_U_B_BDUv2_gloves_OD",
			"CUP_U_B_BDUv2_roll_OD",
			"CUP_U_B_BDUv2_roll_gloves_OD",
			"CUP_U_B_BDUv2_Tpattern",
			"CUP_U_B_BDUv2_gloves_Tpattern",
			"CUP_U_B_BDUv2_roll_Tpattern",
			"CUP_U_B_BDUv2_roll_gloves_Tpattern",
			"CUP_U_B_BDUv2_Tigerstripe",
			"CUP_U_B_BDUv2_gloves_Tigerstripe",
			"CUP_U_B_BDUv2_roll_Tigerstripe",
			"CUP_U_B_BDUv2_roll_gloves_Tigerstripe",
			"CUP_U_B_BDUv2_Urban",
			"CUP_U_B_BDUv2_gloves_Urban",
			"CUP_U_B_BDUv2_roll_Urban",
			"CUP_U_B_BDUv2_roll_gloves_Urban",
		// CUP CDF ==================================================
			"CUP_U_B_CDF_DST_1",
			"CUP_U_B_CDF_DST_2",
			"CUP_U_B_CDF_FST_1",
			"CUP_U_B_CDF_FST_2",
			"CUP_U_B_CDF_MNT_1",
			"CUP_U_B_CDF_MNT_2",
			"CUP_U_B_CDF_SNW_1",
			"CUP_U_B_CDF_SNW_2",
		// CUP ChDKZ ==================================================
			"CUP_U_O_CHDKZ_Kam_02",
			"CUP_U_O_CHDKZ_Commander",
			"CUP_U_O_CHDKZ_Kam_06",
		// CUP Crye ==================================================
			"CUP_U_CRYE_ATACSAU_Full",
			"CUP_U_CRYE_ATACSAU_Roll",
			"CUP_U_CRYE_ATACSFG_Full",
			"CUP_U_CRYE_ATACSFG_Roll",
			"CUP_U_CRYE_BLK_Full",
			"CUP_U_CRYE_BLK_Roll",
			"CUP_U_CRYE_BLK_RUS_Full",
			"CUP_U_CRYE_BLK_RUS_Roll",
			"CUP_U_CRYE_G3C_AOR1",
			"CUP_U_CRYE_G3C_AOR2",
			"CUP_U_CRYE_G3C_ATACSAU",
			"CUP_U_CRYE_G3C_ATACSFG",
			"CUP_U_CRYE_G3C_BLK",
			"CUP_U_CRYE_G3C_M81",
			"CUP_U_CRYE_G3C_RGR",
			"CUP_U_CRYE_RGR_Full",
			"CUP_U_CRYE_RGR_Roll",
			"CUP_U_CRYE_TAN_Full",
			"CUP_U_CRYE_TAN_Roll",
		// CUP GER ==================================================
			"CUP_U_B_GER_Fleck_Crye",
			"CUP_U_B_GER_Fleck_Crye2",
			"CUP_U_B_GER_Crye",
			"CUP_U_B_GER_Crye2",
			"CUP_U_B_GER_Flecktarn_1",
			"CUP_U_B_GER_Flecktarn_2",
			"CUP_U_B_GER_Flecktarn_3",
			"CUP_U_B_GER_Flecktarn_4",
			"CUP_U_B_GER_Flecktarn_5",
			"CUP_U_B_GER_Flecktarn_6",
			"CUP_U_B_GER_Flecktarn_7",
			"CUP_U_B_GER_Flecktarn_8",
			"CUP_U_B_GER_Tropentarn_1",
			"CUP_U_B_GER_Tropentarn_2",
			"CUP_U_B_GER_Tropentarn_3",
			"CUP_U_B_GER_Tropentarn_4",
			"CUP_U_B_GER_Tropentarn_5",
			"CUP_U_B_GER_Tropentarn_6",
			"CUP_U_B_GER_Tropentarn_7",
			"CUP_U_B_GER_Tropentarn_8",
		// CUP HIL ACU ==================================================
			"CUP_U_B_HIL_ACU_CCE",
			"CUP_U_B_HIL_ACU_Gloves_CCE",
			"CUP_U_B_HIL_ACU_Kneepad_CCE",
			"CUP_U_B_HIL_ACU_Kneepad_Gloves_CCE",
			"CUP_U_B_HIL_ACU_TTS",
			"CUP_U_B_HIL_ACU_Gloves_TTS",
			"CUP_U_B_HIL_ACU_Kneepad_TTS",
			"CUP_U_B_HIL_ACU_Kneepad_Gloves_TTS",
		// CUP Partisan ==================================================
			"CUP_U_O_Partisan_TTsKO",
		// CUP SLA ==================================================
			"CUP_U_O_SLA_MixedCamo",
			"CUP_U_O_SLA_Desert",
			"CUP_U_O_SLA_Green",
			"CUP_U_O_SLA_Urban",
		// CUP Takistani ==================================================
			"CUP_U_O_TK_Green",
		// CUP USMC ==================================================
			"CUP_U_B_USMC_MCCUU_M81",
			"CUP_U_B_USMC_MCCUU_M81_gloves",
			"CUP_U_B_USMC_MCCUU_M81_pads",
			"CUP_U_B_USMC_MCCUU_M81_pads_gloves",
			"CUP_U_B_USMC_MCCUU_M81_roll",
			"CUP_U_B_USMC_MCCUU_M81_roll_gloves",
			"CUP_U_B_USMC_MCCUU_M81_roll_pads",
			"CUP_U_B_USMC_MCCUU_M81_roll_pads_gloves",
			"CUP_U_B_USMC_FROG1_WMARPAT",
			"CUP_U_B_USMC_FROG2_WMARPAT",
			"CUP_U_B_USMC_FROG3_WMARPAT",
			"CUP_U_B_USMC_FROG4_WMARPAT",
			"CUP_U_B_USMC_FROG1_DMARPAT",
			"CUP_U_B_USMC_FROG2_DMARPAT",
			"CUP_U_B_USMC_FROG3_DMARPAT",
			"CUP_U_B_USMC_FROG4_DMARPAT",
			"CUP_U_B_USMC_MCCUU",
			"CUP_U_B_USMC_MCCUU_gloves",
			"CUP_U_B_USMC_MCCUU_pads",
			"CUP_U_B_USMC_MCCUU_pads_gloves",
			"CUP_U_B_USMC_MCCUU_roll",
			"CUP_U_B_USMC_MCCUU_roll_gloves",
			"CUP_U_B_USMC_MCCUU_roll_pads",
			"CUP_U_B_USMC_MCCUU_roll_pads_gloves",
			"CUP_U_B_USMC_MCCUU_des",
			"CUP_U_B_USMC_MCCUU_des_gloves",
			"CUP_U_B_USMC_MCCUU_des_pads",
			"CUP_U_B_USMC_MCCUU_des_pads_gloves",
			"CUP_U_B_USMC_MCCUU_des_roll",
			"CUP_U_B_USMC_MCCUU_des_roll_gloves",
			"CUP_U_B_USMC_MCCUU_des_roll_pads",
			"CUP_U_B_USMC_MCCUU_des_roll_pads_gloves",
		// CUP RUS ==================================================
			"CUP_U_O_RUS_BeigeDigital_MSV",
			"CUP_U_O_RUS_BeigeDigital_MSV_gloves_pads",
			"CUP_U_O_RUS_BeigeDigital_MSV_rolled_up",
			"CUP_U_O_RUS_BeigeDigital_MSV_rolled_up_gloves_pads",
			"CUP_U_O_RUS_VSR93_MSV",
			"CUP_U_O_RUS_VSR93_MSV_rolled_up",
			"CUP_U_O_RUS_VSR98_MSV",
			"CUP_U_O_RUS_VSR98_MSV_rolled_up",
			"CUP_U_O_RUS_EMR_1",
			"CUP_U_O_RUS_EMR_gloves_pads",
			"CUP_U_O_RUS_EMR_2",
			"CUP_U_O_RUS_EMR_rolled_up_gloves_pads",
			"CUP_U_O_RUS_Flora_1",
			"CUP_U_O_RUS_Flora_2",
			"CUP_U_O_RUS_BeigeDigital_VDV",
			"CUP_U_O_RUS_BeigeDigital_VDV_gloves_pads",
			"CUP_U_O_RUS_BeigeDigital_VDV_rolled_up",
			"CUP_U_O_RUS_BeigeDigital_VDV_rolled_up_gloves_pads",
			"CUP_U_O_RUS_VSR93_VDV",
			"CUP_U_O_RUS_VSR93_VDV_rolled_up",
			"CUP_U_O_RUS_VSR93_VDV_rolled_up_gloves2",
			"CUP_U_O_RUS_VSR98_VDV",
			"CUP_U_O_RUS_VSR98_VDV_rolled_up",
			"CUP_U_O_RUS_VSR98_VDV_rolled_up_gloves2",
			"CUP_U_O_RUS_EMR_1_VDV",
			"CUP_U_O_RUS_EMR_VDV_gloves_pads",
			"CUP_U_O_RUS_EMR_2_VDV",
			"CUP_U_O_RUS_EMR_VDV_rolled_up_gloves_pads",
			"CUP_U_O_RUS_KSOR_VDV",
			"CUP_U_O_RUS_KSOR_VDV_gloves_pads",
			"CUP_U_O_RUS_KSOR_VDV_rolled_up",
			"CUP_U_O_RUS_KSOR_VDV_rolled_up_gloves_pads",
			"CUP_U_O_RUS_Flora_1_VDV",
			"CUP_U_O_RUS_Flora_2_VDV",
			"CUP_U_O_RUS_Flora_3",
			"CUP_U_O_RUS_M88_MSV",
			"CUP_U_O_RUS_M88_MSV_rolled_up",
			"CUP_U_O_RUS_M88_VDV",
			"CUP_U_O_RUS_M88_VDV_rolled_up",
		// CUP RUS GORKA ==================================================
			"CUP_U_O_RUS_Gorka_Green",
			"CUP_U_O_RUS_Gorka_Green_gloves2",
			"CUP_U_O_RUS_Gorka_Green_gloves_kneepads",
			"CUP_U_O_RUS_Gorka_Partizan",
			"CUP_U_O_RUS_Gorka_Partizan_gloves2",
			"CUP_U_O_RUS_Gorka_Partizan_gloves_kneepads",
			"CUP_U_O_RUS_Gorka_Partizan_A",
			"CUP_U_O_RUS_Gorka_Partizan_A_gloves2",
			"CUP_U_O_RUS_Gorka_Partizan_A_gloves_kneepads",
		// CUP RUS Maskhalat ==================================================
			"CUP_U_O_RUS_Ratnik_BeigeDigital",
			"CUP_U_O_RUS_Ratnik_Summer",
			"CUP_U_O_RUS_Ratnik_Autumn",
			"CUP_U_O_RUS_Ratnik_Desert",
		// CUP ODKB ==================================================
			"CUP_U_O_ODKB_KSOR_VDV",
			"CUP_U_O_ODKB_KSOR_VDV_gloves_pads",
			"CUP_U_O_ODKB_KSOR_VDV_rolled_up",
			"CUP_U_O_ODKB_KSOR_VDV_rolled_up_gloves_pads",
	// ======================================================================
	//			Vanilla
	// ======================================================================
		// VANILLA CBRN ==================================================
			"U_B_CBRN_Suit_01_Tropic_F",
			"U_B_CBRN_Suit_01_Wdl_F",
			"U_I_CBRN_Suit_01_AAF_F",
			"U_I_E_CBRN_Suit_01_EAF_F",
		// VANILLA CTRG ==================================================
			"U_B_CTRG_Soldier_3_Arid_F",
			"U_B_CTRG_Soldier_3_F",
			"U_B_CTRG_Soldier_Arid_F",
			"U_B_CTRG_Soldier_F",
			"U_B_CTRG_Soldier_urb_1_F",
			"U_B_CTRG_Soldier_urb_3_F",
		// VANILLA CombatUniform ==================================================
			"U_I_CombatUniform",
			"U_I_CombatUniform_shortsleeve",
			"U_O_CombatUniform_ocamo",
			"U_O_CombatUniform_oucamo",
		// VANILA Parade ==================================================
			"U_I_E_ParadeUniform_01_LDF_decorated_F",
			"U_I_E_ParadeUniform_01_LDF_F",
			"U_I_ParadeUniform_01_AAF_decorated_F",
			"U_I_ParadeUniform_01_AAF_F",
			"U_O_ParadeUniform_01_CSAT_decorated_F",
			"U_O_ParadeUniform_01_CSAT_F",
		// VANILLA LDF ==================================================
			"U_I_E_Uniform_01_F",
			"U_I_E_Uniform_01_officer_F",
			"U_I_E_Uniform_01_shortsleeve_F",
			"U_I_E_Uniform_01_sweater_F",
		// VANILLA OfficerUniform ==================================================
			"U_I_OfficerUniform",
			"U_O_officer_noInsignia_hex_F",
			"U_O_OfficerUniform_ocamo",
			"U_O_T_Officer_F",
		// VANILLA Gorka ==================================================
			"U_O_R_Gorka_01_black_F",
			"U_O_R_Gorka_01_brown_F",
			"U_O_R_Gorka_01_camo_F",
			"U_O_R_Gorka_01_F",
		// VANILLA SpecopsUniform ==================================================
			"U_O_SpecopsUniform_ocamo",
		// VANILLA Soldier ==================================================
			"U_O_T_Soldier_F",
			"U_O_V_Soldier_Viper_F",
			"U_O_V_Soldier_Viper_hex_F",
		// VANILLA Hydro ==================================================
			"U_O_Wetsuit",
	// ======================================================================
	//			SSU
	// ======================================================================
		// Special Purpose ==================================================
			"U_SSU_Special_Purpose_Suit_AOR1",
			"U_SSU_Special_Purpose_Suit_AOR1_b",
			"U_SSU_Special_Purpose_Suit_AOR2",
			"U_SSU_Special_Purpose_Suit_AOR2_b",
			"U_SSU_Special_Purpose_Suit_MCAM_Black",
			"U_SSU_Special_Purpose_Suit_MCAM_Black_b",
			"U_SSU_Special_Purpose_Suit_Black",
			"U_SSU_Special_Purpose_Suit_Black_b",
			"U_SSU_Special_Purpose_Suit_M81",
			"U_SSU_Special_Purpose_Suit_M81_b",
			"U_SSU_Special_Purpose_Suit_OCP",
			"U_SSU_Special_Purpose_Suit_OCP_b",
			"U_SSU_Special_Purpose_Suit_MCAM_Tropic",
			"U_SSU_Special_Purpose_Suit_MCAM_Tropic_b",
			"U_SSU_Special_Purpose_Suit_MCAM_Woodland",
			"U_SSU_Special_Purpose_Suit_MCAM_Woodland_b",
		// Stealth Uniform ==================================================
			"U_SSU_Stealth_Uniform_AOR1",
			"U_SSU_Stealth_Uniform_Rolled_AOR1",
			"U_SSU_Stealth_Uniform_Sleeved_AOR1",
			"U_SSU_Stealth_Uniform_AOR2",
			"U_SSU_Stealth_Uniform_Rolled_AOR2",
			"U_SSU_Stealth_Uniform_Sleeved_AOR2",
			"U_SSU_Stealth_Uniform_MCAM_Black",
			"U_SSU_Stealth_Uniform_Rolled_MCAM_Black",
			"U_SSU_Stealth_Uniform_Sleeved_MCAM_Black",
			"U_SSU_Stealth_Uniform_Black",
			"U_SSU_Stealth_Uniform_Rolled_Black",
			"U_SSU_Stealth_Uniform_Sleeved_Black",
			"U_SSU_Stealth_Uniform_M81",
			"U_SSU_Stealth_Uniform_Rolled_M81",
			"U_SSU_Stealth_Uniform_Sleeved_M81",
			"U_SSU_Stealth_Uniform_OCP",
			"U_SSU_Stealth_Uniform_Rolled_OCP",
			"U_SSU_Stealth_Uniform_Sleeved_OCP",
			"U_SSU_Stealth_Uniform_MCAM_Black",
			"U_SSU_Stealth_Uniform_MCAM_Tropic",
			"U_SSU_Stealth_Uniform_Rolled_MCAM_Tropic",
			"U_SSU_Stealth_Uniform_Sleeved_MCAM_Tropic",
			"U_SSU_Stealth_Uniform_MCAM_Woodland",
			"U_SSU_Stealth_Uniform_Rolled_MCAM_Woodland",
			"U_SSU_Stealth_Uniform_Sleeved_MCAM_Woodland"
];

_vest = [
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP ACR ==================================================
			"CUP_V_CZ_vest01",
			"CUP_V_CZ_vest02",
			"CUP_V_CZ_vest07",
			"CUP_V_CZ_vest08",
			"CUP_V_CZ_vest11",
			"CUP_V_CZ_vest12",
			"CUP_V_CZ_vest15",
			"CUP_V_CZ_vest16",
			"CUP_V_CZ_NPP2006_nk_black",
			"CUP_V_CZ_NPP2006_vz95_black",
			"CUP_V_CZ_NPP2006_ok_black",
			"CUP_V_CZ_NPP2006_des",
			"CUP_V_CZ_NPP2006_nk_des",
			"CUP_V_CZ_NPP2006_ok_des",
			"CUP_V_CZ_NPP2006_nk_vz95",
			"CUP_V_CZ_NPP2006_vz95",
			"CUP_V_CZ_NPP2006_light_vz95",
			"CUP_V_CZ_NPP2006_ok_vz95",
			"CUP_V_CZ_NPP2006_co_black",
			"CUP_V_CZ_NPP2006_co_des",
			"CUP_V_CZ_NPP2006_co_vz95",
		// CUP BAF ==================================================
			// Комплекты BAF удалены за наличие шевронов с британским флагом
		// CUP SLA ==================================================
			"CUP_V_O_SLA_6B3_1_DES",
			"CUP_V_O_SLA_6B3_1_URB",
			"CUP_V_O_SLA_6B3_1_WDL",
			"CUP_V_O_SLA_Flak_Vest01",
			"CUP_V_O_SLA_Flak_Vest02",
			"CUP_V_O_SLA_Flak_Vest03",
			"CUP_V_O_SLA_6B3_5_DES",
			"CUP_V_O_SLA_6B3_5_URB",
			"CUP_V_O_SLA_6B3_5_WDL",
			"CUP_V_O_SLA_6B3_2_DES",
			"CUP_V_O_SLA_6B3_2_URB",
			"CUP_V_O_SLA_6B3_2_WDL",
			"CUP_V_O_SLA_6B3_3_DES",
			"CUP_V_O_SLA_6B3_3_URB",
			"CUP_V_O_SLA_6B3_3_WDL",
			"CUP_V_O_SLA_M23_1_BRN",
			"CUP_V_O_SLA_M23_1_OD",
			"CUP_V_O_SLA_Carrier_Belt",
			"CUP_V_O_SLA_Carrier_Belt02",
		// CUP RUS ==================================================
			"CUP_V_RUS_6B3_1",
			"CUP_V_RUS_6B3_3",
			"CUP_V_RUS_6B3_4",
			"CUP_V_RUS_6B3_Flora_1",
			"CUP_V_RUS_6B3_Flora_3",
			"CUP_V_RUS_6B3_Flora_4",
			"CUP_V_RUS_6B45_1_BeigeDigital",
			"CUP_V_RUS_6B45_2_BeigeDigital",
			"CUP_V_RUS_6B45_3_BeigeDigital",
			"CUP_V_RUS_6B45_4_BeigeDigital",
			"CUP_V_RUS_6B45_1",
			"CUP_V_RUS_6B45_2",
			"CUP_V_RUS_6B45_3",
			"CUP_V_RUS_6B45_4",
			"CUP_Vest_RUS_6B45_Sh117_BeigeDigital",
			"CUP_Vest_RUS_6B45_Sh117_PKP_BeigeDigital",
			"CUP_Vest_RUS_6B45_Sh117",
			"CUP_Vest_RUS_6B45_Sh117_PKP",
			"CUP_Vest_RUS_6B45_Sh117_Desert",
			"CUP_Vest_RUS_6B45_Sh117_PKP_Desert",
			"CUP_V_RUS_Smersh_1",
			"CUP_V_RUS_Smersh_2",
		// CUP CDF ==================================================
			"CUP_V_CDF_6B3_1_Green",
			"CUP_V_CDF_6B3_2_Green",
			"CUP_V_CDF_6B3_1_DST",
			"CUP_V_CDF_6B3_2_DST",
			"CUP_V_CDF_6B3_1_FST",
			"CUP_V_CDF_6B3_2_FST",
			"CUP_V_CDF_6B3_1_MNT",
			"CUP_V_CDF_6B3_2_MNT",
			"CUP_V_CDF_6B3_1_SNW",
			"CUP_V_CDF_6B3_2_SNW",
			"CUP_V_CDF_CrewBelt",
			"CUP_V_CDF_OfficerBelt",
			"CUP_V_CDF_OfficerBelt2",
			"CUP_V_CDF_6B3_5_Green",
			"CUP_V_CDF_6B3_5_DST",
			"CUP_V_CDF_6B3_5_FST",
			"CUP_V_CDF_6B3_5_MNT",
			"CUP_V_CDF_6B3_5_SNW",
			"CUP_V_CDF_6B3_3_Green",
			"CUP_V_CDF_6B3_3_DST",
			"CUP_V_CDF_6B3_3_FST",
			"CUP_V_CDF_6B3_3_MNT",
			"CUP_V_CDF_6B3_3_SNW",
		// CUP ChDKZ ==================================================
			"CUP_V_O_Ins_Carrier_Rig",
			"CUP_V_O_Ins_Carrier_Rig_Com",
			"CUP_V_O_Ins_Carrier_Rig_Light",
			"CUP_V_O_Ins_Carrier_Rig_MG",
		// CUP CIRAS ==================================================
			"CUP_V_B_Ciras_Black",
			"CUP_V_B_Ciras_Black2",
			"CUP_V_B_Ciras_Black3",
			"CUP_V_B_Ciras_Black4",
			"CUP_V_B_Ciras_Coyote",
			"CUP_V_B_Ciras_Coyote2",
			"CUP_V_B_Ciras_Coyote3",
			"CUP_V_B_Ciras_Coyote4",
			"CUP_V_B_Ciras_Khaki",
			"CUP_V_B_Ciras_Khaki2",
			"CUP_V_B_Ciras_Khaki3",
			"CUP_V_B_Ciras_Khaki4",
			"CUP_V_B_Ciras_Olive",
			"CUP_V_B_Ciras_Olive2",
			"CUP_V_B_Ciras_Olive3",
			"CUP_V_B_Ciras_Olive4",
			"CUP_V_PMC_CIRAS_OD_Empty",
			"CUP_V_PMC_CIRAS_Black_Empty",
			"CUP_V_PMC_CIRAS_Coyote_Empty",
			"CUP_V_PMC_CIRAS_OD_TL",
			"CUP_V_PMC_CIRAS_Black_TL",
			"CUP_V_PMC_CIRAS_Coyote_TL",
			"CUP_V_PMC_CIRAS_OD_Patrol",
			"CUP_V_PMC_CIRAS_Black_Patrol",
			"CUP_V_PMC_CIRAS_Coyote_Patrol",
		// CUP CPC ==================================================
			"CUP_V_CPC_light_coy",
			"CUP_V_CPC_lightbelt_coy",
			"CUP_V_CPC_light_rngr",
			"CUP_V_CPC_lightbelt_rngr",
			"CUP_V_CPC_Fast_coy",
			"CUP_V_CPC_Fastbelt_coy",
			"CUP_V_CPC_Fast_rngr",
			"CUP_V_CPC_Fastbelt_rngr",
			"CUP_V_CPC_tl_coy",
			"CUP_V_CPC_tlbelt_coy",
			"CUP_V_CPC_tl_rngr",
			"CUP_V_CPC_tlbelt_rngr",
		// CUP GER ==================================================
			"CUP_V_B_Armatus_Black",
			"CUP_V_B_Armatus_BB_Black",
			"CUP_V_B_Armatus_Coyote",
			"CUP_V_B_Armatus_BB_Coyote",
			"CUP_V_B_GER_Armatus_Fleck",
			"CUP_V_B_GER_Armatus_BB_Fleck",
			"CUP_V_B_Armatus_OD",
			"CUP_V_B_Armatus_BB_OD",
			"CUP_V_B_GER_Armatus_Trop",
			"CUP_V_B_GER_Armatus_BB_Trop",
			"CUP_V_B_GER_Vest_1",
			"CUP_V_B_GER_Vest_2",
			"CUP_V_B_GER_Carrier_Vest_3",
			"CUP_V_B_JPC_Fleck_Light",
			"CUP_V_B_JPC_Trop_Light",
			"CUP_V_B_LBT_LBV_Black",
			"CUP_V_B_LBT_LBV_Coyote",
			"CUP_V_B_GER_Carrier_Vest",
			"CUP_V_B_LBT_LBV_GRN",
			"CUP_V_B_LBT_LBV_OD",
			"CUP_V_B_GER_Carrier_Vest_2",
			"CUP_V_B_GER_Carrier_Rig_2_Brown",
			"CUP_V_B_GER_Carrier_Rig_3_Brown",
			"CUP_V_B_GER_Carrier_Rig_2",
			"CUP_V_B_GER_Carrier_Rig",
			"CUP_V_B_GER_PVest_Fleck_OFC",
			"CUP_V_B_GER_PVest_Trop_OFC",
			"CUP_V_B_GER_PVest_Fleck_RFL",
			"CUP_V_B_GER_PVest_Fleck_RFL_LT",
			"CUP_V_B_GER_PVest_Trop_RFL",
			"CUP_V_B_GER_PVest_Trop_RFL_LT",
			"CUP_V_B_GER_PVest_Fleck_TL",
			"CUP_V_B_GER_PVest_Fleck_TL_LT",
			"CUP_V_B_GER_PVest_Trop_TL",
			"CUP_V_B_GER_PVest_Trop_TL_LT",
			"CUP_V_B_GER_Tactical_Fleck",
			"CUP_V_B_GER_Tactical_Trop",
			"CUP_V_B_GER_PVest_Fleck_MG",
			"CUP_V_B_GER_PVest_Fleck_MG_LT",
			"CUP_V_B_GER_PVest_Trop_MG",
			"CUP_V_B_GER_PVest_Trop_MG_LT",
		// CUP Interceptor ==================================================
			"CUP_V_B_Interceptor_Base_Coyote",
			"CUP_V_B_Interceptor_Base_DCU",
			"CUP_V_B_Interceptor_Base_Grey",
			"CUP_V_B_Interceptor_Base_M81",
			"CUP_V_B_Interceptor_Base_Olive",
			"CUP_V_B_Interceptor_Rifleman_Coyote",
			"CUP_V_B_Interceptor_Rifleman_DCU",
			"CUP_V_B_Interceptor_Rifleman_Grey",
			"CUP_V_B_Interceptor_Rifleman_M81",
			"CUP_V_B_Interceptor_Rifleman_Olive",
		// CUP IOTV ==================================================
			"CUP_V_B_IOTV_UCP_Empty_USArmy",
			"CUP_V_B_IOTV_UCP_Rifleman_Deltoid_USArmy",
			"CUP_V_B_IOTV_UCP_Rifleman_USArmy",
			"CUP_V_B_IOTV_UCP_SL_USArmy",
			"CUP_V_B_IOTV_UCP_TL_USArmy",
			"CUP_V_B_IOTV_UCP_MG_USArmy",
			"CUP_V_PMC_IOTV_Black_AR",
			"CUP_V_PMC_IOTV_Coyote_AR",
			"CUP_V_PMC_IOTV_Black_Empty",
			"CUP_V_PMC_IOTV_Coyote_Empty",
			"CUP_V_PMC_IOTV_Black_Patrol",
			"CUP_V_PMC_IOTV_Coyote_Patrol",
			"CUP_V_PMC_IOTV_Black_TL",
			"CUP_V_PMC_IOTV_Coyote_TL",
		// CUP JPC ==================================================
			"CUP_V_JPC_Fast_coy",
			"CUP_V_JPC_Fastbelt_coy",
			"CUP_V_JPC_Fast_rngr",
			"CUP_V_JPC_Fastbelt_rngr",
			"CUP_V_B_JPC_Tan_Light",
			"CUP_V_JPC_lightbelt_coy",
			"CUP_V_B_JPC_OD_Light",
			"CUP_V_JPC_lightbelt_rngr",
			"CUP_V_JPC_tl_coy",
			"CUP_V_JPC_tlbelt_coy",
			"CUP_V_JPC_tl_rngr",
			"CUP_V_JPC_tlbelt_rngr",
		// CUP Takistani ==================================================
			"CUP_V_O_TK_Vest_1",
			"CUP_V_O_TK_CrewBelt",
		// CUP MBSS ==================================================
			"CUP_V_B_RRV_DA1_CB",
			"CUP_V_B_RRV_DA2_CB",
			"CUP_V_B_RRV_DA1",
			"CUP_V_B_RRV_DA2",
			"CUP_V_MBSS_PACA_Green",
			"CUP_V_MBSS_PACA2_Green",
			"CUP_V_MBSS_PACA_Black",
			"CUP_V_MBSS_PACA2_Black",
			"CUP_V_MBSS_PACA_CB",
			"CUP_V_MBSS_PACA2_CB",
			"CUP_V_MBSS_PACA_RGR",
			"CUP_V_MBSS_PACA2_RGR",
			"CUP_V_MBSS_PACA_Tan",
			"CUP_V_MBSS_PACA2_Tan",
		// CUP PASGT ==================================================
			"CUP_V_B_PASGT",
			"CUP_V_B_PASGT_no_bags",
			"CUP_V_B_PASGT_CCE",
			"CUP_V_B_PASGT_no_bags_CCE",
			"CUP_V_B_PASGT_OD",
			"CUP_V_B_PASGT_no_bags_OD",
			"CUP_V_B_PASGT_desert",
			"CUP_V_B_PASGT_no_bags_desert",
		// CUP RRV ==================================================
			"CUP_V_B_RRV_Light_CB",
			"CUP_V_B_RRV_Light",
			"CUP_V_B_RRV_Officer_CB",
			"CUP_V_B_RRV_Officer",
			"CUP_V_B_RRV_TL_CB",
			"CUP_V_B_RRV_TL",
			"CUP_V_B_RRV_MG",
			"CUP_V_B_RRV_MG_GRN",
			"CUP_V_B_Delta_1",
			"CUP_V_B_Delta_2",
		// CUP SPC ==================================================
			"CUP_V_B_Eagle_SPC_Empty",
			"CUP_V_B_Eagle_SPC_Officer",
			"CUP_V_B_Eagle_SPC_SL",
			"CUP_V_B_Eagle_SPC_TL",
			"CUP_V_B_Eagle_SPC_Patrol",
			"CUP_V_B_Eagle_SPC_RTO",
			"CUP_V_B_Eagle_SPC_MG",
	// ======================================================================
	//			Vanilla
	// ======================================================================
		// VANILA Bandollier ==================================================
			"V_BandollierB_rgr",
			"V_BandollierB_cbr",
			"V_BandollierB_oli",
			"V_BandollierB_khk",
			"V_BandollierB_blk",
			"V_BandollierB_ghex_F",
		// VANILA Plate Carrier ==================================================
			"V_PlateCarrier1_blk",
			"V_PlateCarrier2_blk",
			"V_PlateCarrier1_rgr_noflag_F",
			"V_PlateCarrier2_rgr_noflag_F",
			"V_PlateCarrierIA1_dgtl",
			"V_PlateCarrierIA2_dgtl",
			"V_PlateCarrierIAGL_dgtl",
			"V_PlateCarrierIAGL_oli",
		// VANILA Plate Carrier ==================================================
			"V_CarrierRigKBT_01_heavy_EAF_F",
			"V_CarrierRigKBT_01_heavy_Olive_F",
			"V_CarrierRigKBT_01_light_Olive_F",
			"V_CarrierRigKBT_01_light_EAF_F",
			"V_CarrierRigKBT_01_Olive_F",
			"V_CarrierRigKBT_01_EAF_F",
		// VANILA Chestrig ==================================================
			"V_Chestrig_blk",
			"V_Chestrig_khk",
			"V_Chestrig_oli",
			"V_Chestrig_rgr",
		// VANILA Harness ==================================================
			"V_HarnessO_brn",
			"V_HarnessOGL_brn",
			"V_HarnessO_ghex_F",
			"V_HarnessOGL_ghex_F",
		// VANILA Leg Strap Bag ==================================================
			"V_LegStrapBag_black_F",
			"V_LegStrapBag_olive_F",
			"V_LegStrapBag_coyote_F",
		// VANILA Rangemaster ==================================================
			"V_Rangemaster_belt",
		// VANILA Tactical Chestrig ==================================================
			"V_TacChestrig_grn_F",
			"V_TacChestrig_oli_F",
			"V_TacChestrig_cbr_F",
		// VANILA Tactical Vest ==================================================
			"V_TacVest_camo",
			"V_TacVest_oli",
			"V_TacVest_khk",
			"V_TacVest_blk",
			"V_TacVest_brn",
		// VANILA Other ==================================================
			"V_RebreatherIR",
	// ======================================================================
	//			SSU
	// ======================================================================
		// SSU Carrier Lite ==================================================
			"V_SSU_Carrier_Lite_AOR1",
			"V_SSU_Carrier_Lite_AOR2",
			"V_SSU_Carrier_Lite_MCAM_Black",
			"V_SSU_Carrier_Lite_Black",
			"V_SSU_Carrier_Lite_M81",
			"V_SSU_Carrier_Lite_OCP",
			"V_SSU_Carrier_Lite_MCAM_Tropic",
			"V_SSU_Carrier_Lite_MCAM_Woodland",
		// SSU Carrier Rig ==================================================
			"V_SSU_Carrier_Rig_AOR1",
			"V_SSU_Carrier_Rig_AOR2",
			"V_SSU_Carrier_Rig_MCAM_Black",
			"V_SSU_Carrier_Rig_Black",
			"V_SSU_Carrier_Rig_M81",
			"V_SSU_Carrier_Rig_OCP",
			"V_SSU_Carrier_Rig_MCAM_Tropic",
			"V_SSU_Carrier_Rig_MCAM_Woodland",
		// SSU Carrier Special Rig ==================================================
			"V_SSU_Carrier_Special_Rig_AOR1",
			"V_SSU_Carrier_Special_Rig_AOR2",
			"V_SSU_Carrier_Special_Rig_MCAM_Black",
			"V_SSU_Carrier_Special_Rig_Black",
			"V_SSU_Carrier_Special_Rig_M81",
			"V_SSU_Carrier_Special_Rig_OCP",
			"V_SSU_Carrier_Special_Rig_MCAM_Tropic",
			"V_SSU_Carrier_Special_Rig_MCAM_Woodland",
		// SSU Modular Carrier Lite ==================================================
			"V_SSU_Modular_Carrier_Lite_AOR1",
			"V_SSU_Modular_Carrier_Lite_AOR2",
			"V_SSU_Modular_Carrier_Lite_MCAM_Black",
			"V_SSU_Modular_Carrier_Lite_Black",
			"V_SSU_Modular_Carrier_Lite_M81",
			"V_SSU_Modular_Carrier_Lite_OCP",
			"V_SSU_Modular_Carrier_Lite_MCAM_Tropic",
			"V_SSU_Modular_Carrier_Lite_MCAM_Woodland",
		// SSU Tactical Chest Rig ==================================================
			"V_SSU_Tactical_Chest_Rig_Arid",
			"V_SSU_Tactical_Chest_Rig_Black",
			"V_SSU_Tactical_Chest_Rig_Green",
			"V_SSU_Tactical_Chest_Rig_Sand",
		// SSU Tactical Chest Rig ==================================================
			"V_SSU_Tactical_Vest_AOR1",
			"V_SSU_Tactical_Vest_AOR2",
			"V_SSU_Tactical_Vest_MCAM_Black",
			"V_SSU_Tactical_Vest_Black",
			"V_SSU_Tactical_Vest_M81",
			"V_SSU_Tactical_Vest_OCP",
			"V_SSU_Tactical_Vest_MCAM_Tropic",
			"V_SSU_Tactical_Vest_MCAM_Woodland"
];

_backpack = [
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP RUS ==================================================
			"CUP_O_RUS_Patrol_bag_BeigeDigital",
			"CUP_O_RUS_Patrol_bag_BeigeDigital_Shovel",
			"CUP_O_RUS_Patrol_bag_Green",
			"CUP_O_RUS_Patrol_bag_Green_Shovel",
			"CUP_O_RUS_Patrol_bag_Summer",
			"CUP_O_RUS_Patrol_bag_Summer_Shovel",
			"CUP_O_RUS_Patrol_bag_Desert",
			"CUP_O_RUS_Patrol_bag_Desert_Shovel",
			"CUP_B_RUS_Backpack",
		// CUP GER ==================================================
			"CUP_B_GER_Pack_Flecktarn",
			"CUP_B_GER_Pack_Tropentarn",
		// CUP ACR ==================================================
			"CUP_B_ACRScout_m95",
			"CUP_B_ACRPara_dpm",
			"CUP_B_ACRPara_m95",
		// CUP US ==================================================
			"CUP_B_USPack_Coyote",
			"CUP_B_USPack_Black",
			"CUP_B_US_Assault_OCP",
			"CUP_B_US_Assault_OEFCP",
			"CUP_B_US_Assault_UCP",
			"CUP_B_US_IIID_OCP",
			"CUP_B_US_IIID_OEFCP",
			"CUP_B_US_IIID_UCP",
		// CUP USMC ==================================================
			"CUP_B_USMC_AssaultPack",
			"CUP_B_USMC_MOLLE",
			"CUP_B_USMC_MOLLE_WDL",
		// CUP Other ==================================================
			"CUP_B_AssaultPack_Coyote",
			"CUP_B_AssaultPack_Black",
			"CUP_B_AssaultPack_ACU",
			"CUP_B_Kombat_Olive",
			"CUP_B_Kombat_Radio_Olive",
			"CUP_B_TacticalPack_CCE",
			"CUP_B_TacticalPack_TTS",
			"CUP_B_Bergen_BAF",
			"CUP_B_AlicePack_Khaki",
			"CUP_B_AlicePack_OD",
			"CUP_B_AlicePack_Bedroll",
	// ======================================================================
	//			VANILA
	// ======================================================================
		// VANILA Assault Pack ==================================================
			"B_AssaultPack_rgr",
			"B_AssaultPack_cbr",
			"B_AssaultPack_sgg",
			"B_AssaultPack_khk",
			"B_AssaultPack_dgtl",
			"B_AssaultPack_blk",
			"B_AssaultPack_tna_F",
			"B_AssaultPack_eaf_F",
			"B_AssaultPack_wdl_F",
		// VANILA Carry all ==================================================
			"B_Carryall_cbr",
			"B_Carryall_oli",
			"B_Carryall_khk",
			"B_Carryall_ghex_F",
			"B_Carryall_eaf_F",
			"B_Carryall_green_F",
			"B_Carryall_wdl_F",
			"B_Carryall_taiga_F",
		// VANILA Field Pack ==================================================
			"B_FieldPack_cbr",
			"B_FieldPack_blk",
			"B_FieldPack_oli",
			"B_FieldPack_khk",
			"B_FieldPack_green_F",
			"B_FieldPack_taiga_F",
			"B_FieldPack_ghex_F",
		// VANILA Kitbag ==================================================
			"B_Kitbag_rgr",
			"B_Kitbag_cbr",
			"B_Kitbag_tan",
			"B_Kitbag_sgg",
		// VANILA Radio Bag ==================================================
			"B_RadioBag_01_eaf_F",
			"B_RadioBag_01_ghex_F",
			"B_RadioBag_01_wdl_F",
			"B_RadioBag_01_tropic_F",
			"B_RadioBag_01_digi_F",
			"B_RadioBag_01_black_F",
		// VANILA Tactical Pack ==================================================
			"B_TacticalPack_rgr",
			"B_TacticalPack_oli",
			"B_TacticalPack_blk",
		// VANILA Viper Light Harness ==================================================
			"B_ViperLightHarness_ghex_F",
			"B_ViperLightHarness_oli_F",
			"B_ViperLightHarness_khk_F",
			"B_ViperLightHarness_blk_F",
		// VANILA Viper Light Harness ==================================================
			"B_ViperHarness_ghex_F",
			"B_ViperHarness_oli_F",
			"B_ViperHarness_khk_F",
			"B_ViperHarness_blk_F",
		// VANILA Leg Strap Bag ==================================================
			"B_LegStrapBag_olive_F",
			"B_LegStrapBag_coyote_F",
			"B_LegStrapBag_black_F",
		// VANILA Other ==================================================
			"B_CombinationUnitRespirator_01_F",
			"B_SCBA_01_F",
			"B_Parachute",
	// ======================================================================
	//			SSU
	// ======================================================================
		// SSU Assault Pack ==================================================
			"B_SSU_Assault_Pack_AOR1",
			"B_SSU_Assault_Pack_AOR2",
			"B_SSU_Assault_Pack_MCAM_Black",
			"B_SSU_Assault_Pack_Black",
			"B_SSU_Assault_Pack_M81",
			"B_SSU_Assault_Pack_OCP",
			"B_SSU_Assault_Pack_MCAM_Tropic",
			"B_SSU_Assault_Pack_MCAM_Woodland",
		// SSU Kitbag ==================================================
			"B_SSU_Kitbag_AOR1",
			"B_SSU_Kitbag_AOR2",
			"B_SSU_Kitbag_MCAM_Black",
			"B_SSU_Kitbag_Black",
			"B_SSU_Kitbag_M81",
			"B_SSU_Kitbag_OCP",
			"B_SSU_Kitbag_MCAM_Tropic",
			"B_SSU_Kitbag_MCAM_Woodland",
		// SSU Leg Strap Bag ==================================================
			"B_SSU_LegStrapBag_AOR1",
			"B_SSU_LegStrapBag_AOR2",
			"B_SSU_LegStrapBag_MCAM_Black",
			"B_SSU_LegStrapBag_Black",
			"B_SSU_LegStrapBag_M81",
			"B_SSU_LegStrapBag_OCP",
			"B_SSU_LegStrapBag_MCAM_Tropic",
			"B_SSU_LegStrapBag_MCAM_Woodland",
		// SSU Leg Strap Bag ==================================================
			"B_SSU_RadioBag_AOR1",
			"B_SSU_RadioBag_AOR2",
			"B_SSU_RadioBag_MCAM_Black",
			"B_SSU_RadioBag_Black",
			"B_SSU_RadioBag_M81",
			"B_SSU_RadioBag_OCP",
			"B_SSU_RadioBag_MCAM_Tropic",
			"B_SSU_RadioBag_MCAM_Woodland",
		// SSU Tactical Pack ==================================================
			"B_SSU_TacticalPack_AOR1",
			"B_SSU_TacticalPack_AOR2",
			"B_SSU_TacticalPack_MCAM_Black",
			"B_SSU_TacticalPack_Black",
			"B_SSU_TacticalPack_M81",
			"B_SSU_TacticalPack_OCP",
			"B_SSU_TacticalPack_MCAM_Tropic",
			"B_SSU_TacticalPack_MCAM_Woodland",
		// SSU Viper Harness ==================================================
			"B_SSU_Viper_Harness_AOR1",
			"B_SSU_Viper_Harness_AOR2",
			"B_SSU_Viper_Harness_MCAM_Black",
			"B_SSU_Viper_Harness_Black",
			"B_SSU_Viper_Harness_M81",
			"B_SSU_Viper_Harness_OCP",
			"B_SSU_Viper_Harness_MCAM_Tropic",
			"B_SSU_Viper_Harness_MCAM_Woodland",
		// SSU Viper Light Harness ==================================================
			"B_SSU_Viper_Light_Harness_AOR1",
			"B_SSU_Viper_Light_Harness_AOR2",
			"B_SSU_Viper_Light_Harness_MCAM_Black",
			"B_SSU_Viper_Light_Harness_Black",
			"B_SSU_Viper_Light_Harness_M81",
			"B_SSU_Viper_Light_Harness_OCP",
			"B_SSU_Viper_Light_Harness_MCAM_Tropic",
			"B_SSU_Viper_Light_Harness_MCAM_Woodland"
];

_headgear = [
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP ACH ==================================================
			"CUP_H_HIL_HelmetACH_CCE",
			"CUP_H_HIL_HelmetACH_Headset_CCE",
			"CUP_H_HIL_HelmetACH_ESS_CCE",
			"CUP_H_HIL_HelmetACH_ESS_Headset_CCE",
			"CUP_H_HIL_HelmetACH_GCovered_CCE",
			"CUP_H_HIL_HelmetACH_GCovered_Headset_CCE",
			"CUP_H_Booniehat_CCE",
			"CUP_H_USArmy_HelmetACH_OCP",
			"CUP_H_USArmy_HelmetACH_GCOVERED_OCP",
			"CUP_H_USArmy_HelmetACH_GCOVERED_Headset_OCP",
			"CUP_H_USArmy_HelmetACH_ESS_OCP",
			"CUP_H_USArmy_HelmetACH_ESS_Headset_OCP",
			"CUP_H_USArmy_HelmetACH_Headset_OCP",
			"CUP_H_USArmy_Boonie_OCP",
			"CUP_H_USArmy_Boonie_hs_OCP",
			"CUP_H_HIL_HelmetACH_TTS",
			"CUP_H_HIL_HelmetACH_Headset_TTS",
			"CUP_H_HIL_HelmetACH_ESS_TTS",
			"CUP_H_HIL_HelmetACH_ESS_Headset_TTS",
			"CUP_H_HIL_HelmetACH_GCovered_TTS",
			"CUP_H_HIL_HelmetACH_GCovered_Headset_TTS",
			"CUP_H_Booniehat_TTS",
			"CUP_H_USArmy_HelmetACH_UCP",
			"CUP_H_USArmy_HelmetACH_GCOVERED_UCP",
			"CUP_H_USArmy_HelmetACH_GCOVERED_Headset_UCP",
			"CUP_H_USArmy_HelmetACH_ESS_UCP",
			"CUP_H_USArmy_HelmetACH_ESS_Headset_UCP",
			"CUP_H_USArmy_HelmetACH_Headset_UCP",
			"CUP_H_USArmy_Boonie_UCP",
			"CUP_H_USArmy_Boonie_hs_UCP",
			"CUP_H_USArmy_Helmet_ECH1_Black",
			"CUP_H_USArmy_Helmet_ECH2_Black",
			"CUP_H_USArmy_Helmet_ECH1_Green",
			"CUP_H_USArmy_Helmet_ECH2_GREEN",
			"CUP_H_USArmy_ECH_MARPAT_des",
			"CUP_H_USArmy_ECH_GCOVEREDMARPAT_des",
			"CUP_H_USArmy_ECH_GCOVERED_Headset_MARPAT_des",
			"CUP_H_USArmy_ECH_ESS_MARPAT_des",
			"CUP_H_USArmy_ECH_ESS_Headset_MARPAT_des",
			"CUP_H_USArmy_ECH_Headset_MARPAT_des",
			"CUP_H_USArmy_ECH_MARPAT",
			"CUP_H_USArmy_ECH_Headset_MARPAT",
			"CUP_H_USArmy_ECH_ESS_MARPAT",
			"CUP_H_USArmy_ECH_ESS_Headset_MARPAT",
			"CUP_H_USArmy_ECH_GCOVERED_MARPAT",
			"CUP_H_USArmy_ECH_GCOVERED_Headset_MARPAT",
			"CUP_H_USArmy_Helmet_ECH1_Sand",
			"CUP_H_USArmy_Helmet_ECH2_Sand",
			"CUP_H_USArmy_Helmet_M1_plain_Olive",
			"CUP_H_USArmy_Helmet_M1_plain_Vine",
			"CUP_H_USArmy_Helmet_M1_plain_M81",
			"CUP_H_USArmy_MICH_M81",
			"CUP_H_USArmy_MICH_Headset_M81",
			"CUP_H_USArmy_MICH_ESS_M81",
			"CUP_H_USArmy_MICH_ESS_Headset_M81",
			"CUP_H_USArmy_MICH_GCOVERED_M81",
			"CUP_H_USArmy_MICH_GCOVERED_Headset_M81",
			"CUP_H_USArmy_MICH_UCP",
			"CUP_H_USArmy_MICH_GCOVERED_UCP",
			"CUP_H_USArmy_MICH_GCOVERED_Headset_UCP",
			"CUP_H_USArmy_MICH_ESS_UCP",
			"CUP_H_USArmy_MICH_ESS_Headset_UCP",
			"CUP_H_USArmy_MICH_Headset_UCP",
			"CUP_H_USArmy_Helmet_Protec",
			"CUP_H_USArmy_Helmet_Protec_Gog",
			"CUP_H_USArmy_Helmet_Protec_Gog_Strb",
			"CUP_H_USArmy_Helmet_Protec_NVG",
		// CUP ACR ==================================================
			"CUP_H_CZ_Hat01",
			"CUP_H_CZ_Hat02",
			"CUP_H_CZ_Hat03",
			"CUP_H_CZ_Booniehat_vz95_des",
			"CUP_H_CZ_Booniehat_fold_des",
			"CUP_H_CZ_Cap_flag",
			"CUP_H_CZ_Cap_Headphones",
			"CUP_H_CZ_Cap_khk",
			"CUP_H_CZ_Cap_Headphones_des",
			"CUP_H_CZ_Cap_rgr",
			"CUP_H_CZ_Hat04",
			"CUP_H_CZ_Helmet01",
			"CUP_H_CZ_Helmet02",
			"CUP_H_CZ_Helmet03",
			"CUP_H_CZ_Helmet04",
			"CUP_H_CZ_Helmet07",
			"CUP_H_CZ_Helmet08",
			"CUP_H_CZ_Helmet09",
			"CUP_H_CZ_Helmet10",
			"CUP_H_CZ_Patrol_Cap",
		// CUP CDF ==================================================
			"CUP_H_CDF_Beret_UN",
			"CUP_H_CDF_OfficerCap_DST",
			"CUP_H_CDF_OfficerCap_MNT",
			"CUP_H_CDF_OfficerCap_FST",
			"CUP_H_CDF_OfficerCap_SNW",
			"CUP_H_CDF_H_PASGT_DST",
			"CUP_H_CDF_H_PASGT_FST",
			"CUP_H_CDF_H_PASGT_MNT",
			"CUP_H_CDF_H_PASGT_SNW",
		// CUP ChDKZ ==================================================
			"CUP_H_ChDKZ_Beanie",
			"CUP_H_ChDKZ_Beret",
			"CUP_H_ChDKZ_Cap",
		// CUP FR ==================================================
			"CUP_H_FR_BandanaGreen",
			"CUP_H_FR_BandanaWdl",
			"CUP_H_FR_Bandana_Headset",
			"CUP_H_FR_BeanieGreen",
			"CUP_H_FR_Boonie_DES",
			"CUP_H_FR_BoonieMARPAT",
			"CUP_H_FR_BoonieWDL",
			"CUP_H_FR_PRR_BoonieWDL",
			"CUP_H_FR_Cap_Headset_Green",
			"CUP_H_FR_Cap_Officer_Headset",
			"CUP_H_FR_ECH",
		// CUP GER ==================================================
			"CUP_H_Ger_Beret_INF_Grn",
			"CUP_H_Ger_Beret_KSK_Red",
			"CUP_H_Ger_Beret_ARM_Grn",
			"CUP_H_Ger_Beret_ARM_Blk",
			"CUP_H_Ger_Boonie_Flecktarn",
			"CUP_H_Ger_Boonie2_Flecktarn",
			"CUP_H_Ger_Boonie_desert",
			"CUP_H_Ger_Boonie2_desert",
			"CUP_H_Ger_Cap_EP_Grn2",
			"CUP_H_Ger_Cap_EP_Grn1",
			"CUP_H_Ger_Cap_Grn2",
			"CUP_H_Ger_Cap_Grn1",
			"CUP_H_Ger_Cap_EP_Tan2",
			"CUP_H_Ger_Cap_EP_Tan1",
			"CUP_H_Ger_Cap_Tan2",
			"CUP_H_Ger_Cap_Tan1",
			"CUP_H_Ger_M92_Black",
			"CUP_H_Ger_M92_Black_GG",
			"CUP_H_Ger_M92_Black_GG_CF",
			"CUP_H_Ger_M92_Black_GG_CB",
			"CUP_H_Ger_M92_Cover",
			"CUP_H_Ger_M92_Cover_GG",
			"CUP_H_Ger_M92_Cover_GG_CF",
			"CUP_H_Ger_M92_Cover_GG_CB",
			"CUP_H_Ger_M92",
			"CUP_H_Ger_M92_GG",
			"CUP_H_Ger_M92_GG_CF",
			"CUP_H_Ger_M92_GG_CB",
			"CUP_H_Ger_M92_RGR",
			"CUP_H_Ger_M92_RGR_GG",
			"CUP_H_Ger_M92_RGR_GG_CF",
			"CUP_H_Ger_M92_RGR_GG_CB",
			"CUP_H_Ger_M92_Tan",
			"CUP_H_Ger_M92_Tan_GG",
			"CUP_H_Ger_M92_Tan_GG_CB",
			"CUP_H_Ger_M92_Tan_GG_CF",
			"CUP_H_Ger_M92_Cover_Trop",
			"CUP_H_Ger_M92_Cover_Trop_GG_CB",
			"CUP_H_Ger_M92_Cover_Trop_GG_CF",
			"CUP_H_Ger_M92_Cover_Trop_GG",
		// CUP LWH ==================================================
			"CUP_H_LWHv2_brown",
			"CUP_H_LWHv2_brown_comms",
			"CUP_H_LWHv2_brown_ess_comms",
			"CUP_H_LWHv2_desert",
			"CUP_H_LWHv2_desert_comms",
			"CUP_H_LWHv2_desert_ess_comms",
			"CUP_H_LWHv2_ERDL_lowland",
			"CUP_H_LWHv2_ERDL_lowland_comms",
			"CUP_H_LWHv2_ERDL_lowland_ess_comms",
			"CUP_H_LWHv2_MARPAT_des",
			"CUP_H_LWHv2_MARPAT_des_comms",
			"CUP_H_LWHv2_MARPAT_des_cov_fr",
			"CUP_H_LWHv2_MARPAT_des_comms_cov_fr",
			"CUP_H_LWHv2_MARPAT_des_NVG_gog_cov2",
			"CUP_H_LWHv2_MARPAT_des_NVG_gog2_cov2",
			"CUP_H_LWHv2_MARPAT",
			"CUP_H_LWHv2_MARPAT_comms",
			"CUP_H_LWHv2_MARPAT_comms_cov_fr",
			"CUP_H_LWHv2_MARPAT_cov_fr",
			"CUP_H_LWHv2_MARPAT_NVG_gog_cov2",
			"CUP_H_LWHv2_MARPAT_NVG_gog2_cov2",
			"CUP_H_LWHv2_OD",
			"CUP_H_LWHv2_OD_comms",
			"CUP_H_LWHv2_OD_ess_comms",
			"CUP_H_LWHv2_Tpat",
			"CUP_H_LWHv2_Tpat_comms",
			"CUP_H_LWHv2_Tpat_ess_comms",
			"CUP_H_LWHv2_tigerstripe",
			"CUP_H_LWHv2_tigerstripe_comms",
			"CUP_H_LWHv2_tigerstripe_ess_comms",
		// CUP OpsCore ==================================================
			"CUP_H_OpsCore_Covered_AAF",
			"CUP_H_OpsCore_Covered_AAF_SF",
			"CUP_H_OpsCore_Covered_AAF_NoHS",
			"CUP_H_OpsCore_Black",
			"CUP_H_OpsCore_Black_SF",
			"CUP_H_OpsCore_Black_NoHS",
			"CUP_H_OpsCore_Covered_Fleck",
			"CUP_H_OpsCore_Covered_Fleck_SF",
			"CUP_H_OpsCore_Covered_Fleck_NoHS",
			"CUP_H_OpsCore_Green",
			"CUP_H_OpsCore_Green_SF",
			"CUP_H_OpsCore_Green_NoHS",
			"CUP_H_OpsCore_Grey",
			"CUP_H_OpsCore_Grey_SF",
			"CUP_H_OpsCore_Grey_NoHS",
			"CUP_H_OpsCore_Spray",
			"CUP_H_OpsCore_Spray_SF",
			"CUP_H_OpsCore_Spray_NoHS",
			"CUP_H_OpsCore_Covered_Tigerstripe",
			"CUP_H_OpsCore_Covered_Tigerstripe_SF",
			"CUP_H_OpsCore_Covered_Tigerstripe_NoHS",
			"CUP_H_OpsCore_Covered_Tropen",
			"CUP_H_OpsCore_Covered_Tropen_SF",
			"CUP_H_OpsCore_Covered_Tropen_NoHS",
			"CUP_H_OpsCore_Tan",
			"CUP_H_OpsCore_Tan_SF",
			"CUP_H_OpsCore_Tan_NoHS",
			"CUP_H_OpsCore_Covered_UCP",
			"CUP_H_OpsCore_Covered_UCP_SF",
			"CUP_H_OpsCore_Covered_UCP_NoHS",
		// CUP PASGT ==================================================
			"CUP_H_PASGTv2_DCU",
			"CUP_H_PASGTv2_desert",
			"CUP_H_PASGTv2_ERDL_highland",
			"CUP_H_PASGTv2_ERDL_lowland",
			"CUP_H_PASGTv2_WDL",
			"CUP_H_PASGTv2_WDL_CF",
			"CUP_H_PASGTv2_WDL_GG",
			"CUP_H_PASGTv2_NVG_WDL",
			"CUP_H_PASGTv2_NVG_WDL_GG",
			"CUP_H_PASGTv2_NVG_WDL_CF",
			"CUP_H_PASGTv2_NVG_WDL_GG_CB",
			"CUP_H_PASGTv2_NVG_DCU",
			"CUP_H_PASGTv2_NVG_desert",
			"CUP_H_PASGTv2_NVG_ERDL_highland",
			"CUP_H_PASGTv2_NVG_ERDL_lowland",
			"CUP_H_PASGTv2_tigerstripe",
			"CUP_H_PASGTv2_NVG_tigerstripe",
			"CUP_H_PASGTv2_OD",
			"CUP_H_PASGTv2_NVG_OD",
			"CUP_H_PASGTv2_TPattern",
			"CUP_H_PASGTv2_NVG_TPattern",
			"CUP_H_PASGTv2_Urban",
			"CUP_H_PASGTv2_NVG_Urban",
		// CUP PMC ==================================================
			"CUP_H_PMC_Beanie_Khaki",
			"CUP_H_PMC_Beanie_Black",
			"CUP_H_PMC_Beanie_Headphones_Khaki",
			"CUP_H_PMC_Beanie_Headphones_Black",
			"CUP_H_PMC_Cap_Grey",
			"CUP_H_PMC_Cap_PRR_Grey",
			"CUP_H_PMC_Cap_Back_PRR_Grey",
			"CUP_H_PMC_Cap_EP_Grey",
			"CUP_H_PMC_Cap_Back_EP_Grey",
			"CUP_H_PMC_Cap_Back_Grey",
			"CUP_H_PMC_Cap_Tan",
			"CUP_H_PMC_Cap_Back_Tan",
			"CUP_H_PMC_Cap_Back_EP_Tan",
			"CUP_H_PMC_Cap_Back_PRR_Tan",
			"CUP_H_PMC_Cap_EP_Tan",
			"CUP_H_PMC_Cap_PRR_Tan",
		// CUP RACS ==================================================
			"CUP_H_RACS_Beret_Blue",
		// CUP RUS ==================================================
			"CUP_H_RUS_6B27_cover_BeigeDigital",
			"CUP_H_RUS_6B27_cover_BeigeDigital_goggles",
			"CUP_H_RUS_6B27_cover_BeigeDigital_headset",
			"CUP_H_RUS_6B27_cover_BeigeDigital_headset_goggles",
			"CUP_H_RUS_6B46",
			"CUP_H_RUS_6B27_cover",
			"CUP_H_RUS_6B27_cover_headset",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"CUP_H_RUS_6B27_olive",
			"CUP_H_RUS_6B27_NVG_olive",
			"CUP_H_RUS_6B27",
			"CUP_H_RUS_6B27_NVG",
			"CUP_H_RUS_6B27_headset",
			"CUP_H_RUS_6B27_goggles",
			"CUP_H_RUS_6B27_headset_goggles",
			"CUP_H_RUS_6B47_v2_BeigeDigital",
			"CUP_H_RUS_6B47_v2_GogglesDown_BeigeDigital",
			"CUP_H_RUS_6B47_v2_GogglesUp_BeigeDigital",
			"CUP_H_RUS_6B47_v2_GogglesClosed_BeigeDigital",
			"CUP_H_RUS_6B47_v2_Summer",
			"CUP_H_RUS_6B47_v2_GogglesDown_Summer",
			"CUP_H_RUS_6B47_v2_GogglesUp_Summer",
			"CUP_H_RUS_6B47_v2_GogglesClosed_Summer",
			"CUP_H_RUS_6B47_v2_Desert",
			"CUP_H_RUS_6B47_v2_GogglesClosed_Desert",
			"CUP_H_RUS_6B47_v2_GogglesDown_Desert",
			"CUP_H_RUS_6B47_v2_GogglesUp_Desert",
			"CUP_H_RUS_6B47",
			"CUP_H_RUS_6B47_headset",
			"CUP_H_RUS_6B47_headset_goggles",
			"CUP_H_RUS_6B47_desert",
			"CUP_H_RUS_6B47_headset_desert",
			"CUP_H_RUS_6B47_goggles_desert",
			"CUP_H_RUS_6B47_headset_goggles_desert",
			"CUP_H_RUS_6B47_SF",
			"CUP_H_RUS_6B47_SF_headset",
			"CUP_H_RUS_6B47_SF_headset_desert",
			"CUP_H_RUS_6B47_SF_headset_goggles_desert",
			"CUP_H_RUS_6B47_SF_headset_goggles_black",
			"CUP_H_RUS_6B47_SF_headset_black",
			"CUP_H_RUS_Altyn",
			"CUP_H_RUS_Altyn_Shield_Up",
			"CUP_H_RUS_Altyn_Shield_Down",
			"CUP_H_RUS_Altyn_Goggles",
			"CUP_H_RUS_Altyn_black",
			"CUP_H_RUS_Altyn_Shield_Up_black",
			"CUP_H_RUS_Altyn_Shield_Down_black",
			"CUP_H_RUS_Altyn_Goggles_black",
			"CUP_H_RUS_Altyn_khaki",
			"CUP_H_RUS_Altyn_Shield_Up_khaki",
			"CUP_H_RUS_Altyn_Shield_Down_khaki",
			"CUP_H_RUS_Altyn_Goggles_khaki",
			"CUP_H_RUS_Bandana_GSSh_Headphones",
			"CUP_H_RUS_Bandana_HS",
			"CUP_H_RUS_Beret_VDV",
			"CUP_H_RUS_Beret_Spetsnaz",
			"CUP_H_RUS_K6_3",
			"CUP_H_RUS_K6_3_Shield_Up",
			"CUP_H_RUS_K6_3_Shield_Down",
			"CUP_H_RUS_K6_3_Goggles",
			"CUP_H_RUS_K6_3_black",
			"CUP_H_RUS_K6_3_Shield_Up_black",
			"CUP_H_RUS_K6_3_Shield_Down_black",
			"CUP_H_RUS_K6_3_Goggles_black",
			"CUP_H_RUS_K6_3_khaki",
			"CUP_H_RUS_K6_3_Shield_Up_khaki",
			"CUP_H_RUS_K6_3_Shield_Down_khaki",
			"CUP_H_RUS_K6_3_Goggles_khaki",
			"CUP_H_RUS_SSH68_olive",
			"CUP_H_RUS_SSH68_green",
			"CUP_H_RUS_SSH68_cover_vsr93",
			"CUP_H_RUS_SSH68_cover_vsr98",
			"CUP_H_RUS_SSH68_cover_vsr84_dubok",
			"CUP_H_RUS_SSH68_cover_berezka",
			"CUP_H_RUS_GSSh01_Headphones_black",
			"CUP_H_RUS_GSSh01_Headphones_brown",
			"CUP_H_RUS_GSSh01_Headphones_grey",
			"CUP_H_RUS_GSSh01_Headphones_green",
			"CUP_H_RUS_Cap_ATACSAU",
			"CUP_H_RUS_Cap_ATACSFG",
			"CUP_H_RUS_Cap_EMR",
		// CUP SLA ==================================================
			"CUP_H_SLA_BeanieGreen",
			"CUP_H_SLA_Beret",
			"CUP_H_SLA_BeretRed",
			"CUP_H_SLA_Boonie_DES",
			"CUP_H_SLA_Boonie_URB",
			"CUP_H_SLA_Boonie",
			"CUP_H_SLA_SLCap",
			"CUP_H_SLA_OfficerCap",
			"CUP_H_SLA_Helmet",
			"CUP_H_SLA_Helmet_DES",
			"CUP_H_SLA_Helmet_URB",
			"CUP_H_SLA_Helmet_BLK",
		// CUP Takistani ==================================================
			"CUP_H_TK_Beret",
		// CUP US ==================================================
			"CUP_H_US_BOONIE_Alpenflage",
			"CUP_H_USA_Boonie_wdl",
			"CUP_H_USA_Cap_M81",
			"CUP_H_US_patrol_cap_alpenflage",
			"CUP_H_US_patrol_cap_DCU",
			"CUP_H_US_patrol_cap_desert",
			"CUP_H_US_patrol_cap_ERDL_highland",
			"CUP_H_US_patrol_cap_ERDL",
			"CUP_H_US_patrol_cap_WDL",
			"CUP_H_US_patrol_cap_OD",
			"CUP_H_US_patrol_cap_tigerstripe",
			"CUP_H_US_patrol_cap_Tpattern",
			"CUP_H_US_patrol_cap_urban",
			"CUP_H_US_patrol_cap_UCP",
		// CUP USMC ==================================================
			"CUP_H_USMC_BOONIE_2_DES",
			"CUP_H_USMC_BOONIE_WDL",
			"CUP_H_USMC_BOONIE_PRR_DES",
			"CUP_H_USMC_BOONIE_PRR_WDL",
			"CUP_H_USMC_Officer_Cap",
			"CUP_H_USMC_CAP_WDL",
			"CUP_H_USMC_CAP_PRR_WDL",
			"CUP_H_USMC_CAP_DES",
			"CUP_H_USMC_CAP_PRR_DES",
	// ======================================================================
	//			VANILA
	// ======================================================================
		// VANILA MilCap ==================================================
			"H_MilCap_dgtl",
			"H_MilCap_eaf",
			"H_MilCap_ghex_F",
			"H_MilCap_grn",
			"H_MilCap_gry",
			"H_MilCap_ocamo",
			"H_MilCap_taiga",
			"H_MilCap_tna_F",
			"H_MilCap_wdl",
		// VANILA Bandanna ==================================================
			"H_Bandanna_camo",
			"H_Bandanna_cbr",
			"H_Bandanna_gry",
			"H_Bandanna_khk",
			"H_Bandanna_khk_hs",
			"H_Bandanna_sand",
			"H_Bandanna_sgg",
		// VANILA Beret ==================================================
			"H_Beret_blk",
			"H_Beret_CSAT_01_F",
			"H_Beret_EAF_01_F",
		// VANILA Cap ==================================================
			"H_Cap_blk",
			"H_Cap_blk_Raven",
			"H_Cap_brn_SPECOPS",
			"H_Cap_grn",
			"H_Cap_oli",
			"H_Cap_oli_hs",
			"H_Cap_tan",
		// VANILA Helmet B ==================================================
			"H_HelmetB_black",
			"H_HelmetB_Enh_tna_F",
			"H_HelmetB_light_black",
			"H_HelmetB_Light_tna_F",
			"H_HelmetB_light_wdl",
			"H_HelmetB_plain_wdl",
			"H_HelmetB_TI_arid_F",
			"H_HelmetB_TI_tna_F",
			"H_HelmetB_tna_F",
		// VANILA HelmetIA ==================================================
			"H_HelmetIA",
		// VANILA Booniehat ==================================================
			"H_Booniehat_dgtl",
			"H_Booniehat_eaf",
			"H_Booniehat_khk",
			"H_Booniehat_khk_hs",
			"H_Booniehat_mgrn",
			"H_Booniehat_oli",
			"H_Booniehat_taiga",
			"H_Booniehat_tan",
			"H_Booniehat_tna_F",
			"H_Booniehat_wdl",
		// VANILA Helmet Spec B ==================================================
			"H_HelmetSpecB_blk",
			"H_HelmetSpecB_wdl",
		// VANILA Watchcap ==================================================
			"H_Watchcap_blk",
			"H_Watchcap_camo",
			"H_Watchcap_cbr",
			"H_Watchcap_khk",
		// VANILA Shemag ==================================================
			"H_Shemag_olive",
			"H_Shemag_olive_hs",
			"H_ShemagOpen_tan",
		// VANILA Helmet Spec O ==================================================
			"H_HelmetSpecO_blk",
			"H_HelmetSpecO_ghex_F",
			"H_HelmetSpecO_ocamo",
		// VANILA Helmet Leader O ==================================================
			"H_HelmetLeaderO_ghex_F",
			"H_HelmetLeaderO_ocamo",
			"H_HelmetLeaderO_oucamo",
		// VANILA Helmet O ==================================================
			"H_HelmetO_ghex_F",
			"H_HelmetO_ocamo",
			"H_HelmetO_oucamo",
		// VANILA HelmetB TI ==================================================
			"H_HelmetB_TI_tna_F",
			"H_HelmetB_TI_arid_F",
		// VANILA Helmet HBK ==================================================
			"H_HelmetHBK_chops_F",
			"H_HelmetHBK_ear_F",
			"H_HelmetHBK_F",
			"H_HelmetHBK_headset_F",
		// VANILA Helmet Aggressor ==================================================
			"H_HelmetAggressor_cover_F",
			"H_HelmetAggressor_cover_taiga_F",
			"H_HelmetAggressor_F",
		// VANILA PASGT ==================================================
			"H_PASGT_basic_black_F",
			"H_PASGT_basic_olive_F",
		// VANILA Parade ==================================================
			"H_ParadeDressCap_01_AAF_F",
			"H_ParadeDressCap_01_CSAT_F",
			"H_ParadeDressCap_01_LDF_F",
	// ======================================================================
	//			SSU
	// ======================================================================
		// SSU Advanced Modular Helmet ==================================================
			"H_SSU_Advanced_Modular_Helmet_HS_AOR1",
			"H_SSU_Advanced_Modular_Helmet_Chops_AOR1",
			"H_SSU_Advanced_Modular_Helmet_Ear_AOR1",
			"H_SSU_Advanced_Modular_Helmet_HS_AOR2",
			"H_SSU_Advanced_Modular_Helmet_Chops_AOR2",
			"H_SSU_Advanced_Modular_Helmet_Ear_AOR2",
			"H_SSU_Advanced_Modular_Helmet_HS_MCAM_Black",
			"H_SSU_Advanced_Modular_Helmet_Chops_MCAM_Black",
			"H_SSU_Advanced_Modular_Helmet_Ear_MCAM_Black",
			"H_SSU_Advanced_Modular_Helmet_HS_Black",
			"H_SSU_Advanced_Modular_Helmet_Chops_Black",
			"H_SSU_Advanced_Modular_Helmet_Ear_Black",
			"H_SSU_Advanced_Modular_Helmet_HS_M81",
			"H_SSU_Advanced_Modular_Helmet_Chops_M81",
			"H_SSU_Advanced_Modular_Helmet_Ear_M81",
			"H_SSU_Advanced_Modular_Helmet_HS_OCP",
			"H_SSU_Advanced_Modular_Helmet_Chops_OCP",
			"H_SSU_Advanced_Modular_Helmet_Ear_OCP",
			"H_SSU_Advanced_Modular_Helmet_HS_MCAM_Tropic",
			"H_SSU_Advanced_Modular_Helmet_Chops_MCAM_Tropic",
			"H_SSU_Advanced_Modular_Helmet_Ear_MCAM_Tropic",
			"H_SSU_Advanced_Modular_Helmet_HS_MCAM_Woodland",
			"H_SSU_Advanced_Modular_Helmet_Chops_MCAM_Woodland",
			"H_SSU_Advanced_Modular_Helmet_Ear_MCAM_Woodland",
		// SSU Boonie ==================================================
			"H_SSU_Boonie_HS_AOR1",
			"H_SSU_Boonie_HS_AOR2",
			"H_SSU_Boonie_HS_MCAM_Black",
			"H_SSU_Boonie_HS_Black",
			"H_SSU_Boonie_HS_M81",
			"H_SSU_Boonie_HS_MCAM",
			"H_SSU_Boonie_HS_OCP",
			"H_SSU_Boonie_HS_MCAM_Tropic",
			"H_SSU_Boonie_HS_MCAM_Woodland",
		// SSU Cap ==================================================
			"H_SSU_Cap_HS_AOR1",
			"H_SSU_Cap_HS_AOR2",
			"H_SSU_Cap_HS_MCAM_Black",
			"H_SSU_Cap_HS_Black",
			"H_SSU_Cap_HS_M81",
			"H_SSU_Cap_HS_OCP",
			"H_SSU_Cap_HS_MCAM_Tropic",
			"H_SSU_Cap_HS_MCAM_Woodland",
		// SSU Light Combat Helmet ==================================================
			"H_SSU_Light_Combat_Helmet_AOR1",
			"H_SSU_Light_Combat_Helmet_AOR2",
			"H_SSU_Light_Combat_Helmet_MCAM_Black",
			"H_SSU_Light_Combat_Helmet_Black",
			"H_SSU_Light_Combat_Helmet_M81",
			"H_SSU_Light_Combat_Helmet_OCP",
			"H_SSU_Light_Combat_Helmet_MCAM_Tropic",
			"H_SSU_Light_Combat_Helmet_MCAM_Woodland",
		// SSU Combat Helmet ==================================================
			"H_SSU_Combat_Helmet_AOR1",
			"H_SSU_Combat_Helmet_AOR2",
			"H_SSU_Combat_Helmet_MCAM_Black",
			"H_SSU_Combat_Helmet_Black",
			"H_SSU_Combat_Helmet_M81",
			"H_SSU_Combat_Helmet_OCP",
			"H_SSU_Combat_Helmet_MCAM_Tropic",
			"H_SSU_Combat_Helmet_MCAM_Woodland",
		// SSU Camo Combat Helmet ==================================================
			"H_SSU_Camo_Combat_Helmet_AOR1",
			"H_SSU_Camo_Combat_Helmet_AOR2",
			"H_SSU_Camo_Combat_Helmet_MCAM_Black",
			"H_SSU_Camo_Combat_Helmet_Black",
			"H_SSU_Camo_Combat_Helmet_M81",
			"H_SSU_Camo_Combat_Helmet_MCAM_Tropic",
			"H_SSU_Camo_Combat_Helmet_MCAM_Woodland",
		// SSU Enhanced Combat Helmet ==================================================
			"H_SSU_Enhanced_Combat_Helmet_AOR1",
			"H_SSU_Enhanced_Combat_Helmet_AOR2",
			"H_SSU_Enhanced_Combat_Helmet_MCAM_Black",
			"H_SSU_Enhanced_Combat_Helmet_Black",
			"H_SSU_Enhanced_Combat_Helmet_M81",
			"H_SSU_Enhanced_Combat_Helmet_OCP",
			"H_SSU_Enhanced_Combat_Helmet_MCAM_Tropic",
			"H_SSU_Enhanced_Combat_Helmet_MCAM_Woodland",
		// SSU Stealth Combat Helmet ==================================================
			"H_SSU_Stealth_Combat_Helmet_AOR1",
			"H_SSU_Stealth_Combat_Helmet_AOR2",
			"H_SSU_Stealth_Combat_Helmet_MCAM_Black",
			"H_SSU_Stealth_Combat_Helmet_Black",
			"H_SSU_Stealth_Combat_Helmet_Black_b",
			"H_SSU_Stealth_Combat_Helmet_M81",
			"H_SSU_Stealth_Combat_Helmet_OCP",
			"H_SSU_Stealth_Combat_Helmet_MCAM_Tropic",
			"H_SSU_Stealth_Combat_Helmet_MCAM_Woodland"
];

_googles = [
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP Beard ==================================================
			"CUP_Beard_Black",
			"CUP_Beard_Blonde",
			"CUP_Beard_Brown",
		// CUP RUS ==================================================
			"CUP_RUS_Balaclava_blk",
			"CUP_RUS_Balaclava_emr",
			"CUP_RUS_Balaclava_grn",
			"CUP_RUS_Balaclava_rgr",
			"CUP_G_RUS_Balaclava_Ratnik",
			"CUP_G_RUS_Balaclava_Ratnik_v2",
			"CUP_RUS_Balaclava_tan",
		// CUP ESS ==================================================
			"CUP_G_ESS_BLK_Dark",
			"CUP_G_ESS_BLK_Ember",
			"CUP_G_ESS_BLK",
			"CUP_G_ESS_RGR_Dark",
			"CUP_G_ESS_RGR_Ember",
			"CUP_G_ESS_RGR",
			"CUP_G_ESS_CBR_Dark",
			"CUP_G_ESS_CBR_Ember",
			"CUP_G_ESS_CBR",
			"CUP_G_ESS_KHK_Dark",
			"CUP_G_ESS_KHK_Ember",
			"CUP_G_ESS_KHK",
			"CUP_G_ESS_BLK_Facewrap_Black",
			"CUP_G_ESS_RGR_Facewrap_Ranger",
			"CUP_G_ESS_RGR_Facewrap_Skull",
			"CUP_G_ESS_RGR_Facewrap_Tropical",
			"CUP_G_ESS_KHK_Facewrap_Tan",
			"CUP_G_ESS_BLK_Scarf_Blk",
			"CUP_G_ESS_BLK_Scarf_Grn",
			"CUP_G_ESS_KHK_Scarf_Tan",
			"CUP_G_ESS_BLK_Scarf_Face_Blk",
			"CUP_G_ESS_BLK_Scarf_Face_Grn",
			"CUP_G_ESS_KHK_Scarf_Face_Tan",
		// CUP PMC ==================================================
			"CUP_PMC_Facewrap_Black",
			"CUP_PMC_Facewrap_Ranger",
			"CUP_PMC_Facewrap_Skull",
			"CUP_PMC_Facewrap_Tropical",
			"CUP_PMC_Facewrap_Tan",
			"CUP_G_PMC_Facewrap_Black_Glasses_Dark_Headset",
			"CUP_G_PMC_Facewrap_Black_Glasses_Dark",
			"CUP_G_PMC_Facewrap_Black_Glasses_Ember",
			"CUP_G_PMC_Facewrap_Tropical_Glasses_Dark_Headset",
			"CUP_G_PMC_Facewrap_Tropical_Glasses_Dark",
			"CUP_G_PMC_Facewrap_Tropical_Glasses_Ember",
			"CUP_G_PMC_Facewrap_Tan_Glasses_Dark_Headset",
			"CUP_G_PMC_Facewrap_Tan_Glasses_Dark",
			"CUP_G_PMC_Facewrap_Tan_Glasses_Ember",
			"CUP_G_PMC_RadioHeadset",
			"CUP_G_PMC_RadioHeadset_Glasses",
			"CUP_G_PMC_RadioHeadset_Glasses_Dark",
			"CUP_G_PMC_RadioHeadset_Glasses_Ember",
		// CUP Scarf ==================================================
			"CUP_G_Scarf_Face_Blk",
			"CUP_G_Scarf_Face_Grn",
			"CUP_G_Scarf_Face_Tan",
			"CUP_G_Grn_Scarf_Shades",
			"CUP_G_Tan_Scarf_Shades",
		// CUP Oakleys ==================================================
			"CUP_G_Oakleys_Clr",
			"CUP_G_Oakleys_Drk",
			"CUP_G_Oakleys_Embr",
		// CUP FR ==================================================
			"CUP_FR_NeckScarf3",
			"CUP_FR_NeckScarf",
			"CUP_FR_NeckScarf2",
	// ======================================================================
	//			VANILA
	// ======================================================================
		"G_Aviator",
		"G_Balaclava_combat",
		"G_Balaclava_oli",
		"G_Balaclava_lowprofile",
		"G_Balaclava_blk",
		"G_Balaclava_TI_tna_F",
		"G_Balaclava_TI_G_tna_F",
		"G_Balaclava_TI_blk_F",
		"G_Balaclava_TI_G_blk_F",
		"G_Bandanna_aviator",
		"G_Bandanna_beast",
		"G_Bandanna_tan",
		"G_Bandanna_oli",
		"G_Bandanna_sport",
		"G_Bandanna_shades",
		"G_Bandanna_khk",
		"G_Bandanna_blk",
		"G_Combat",
		"G_Diving",
		"G_I_Diving",
		"G_O_Diving",
		"G_Shades_Green",
		"G_Shades_Red",
		"G_Tactical_Black",
		"G_Tactical_Clear",
		"G_Combat_Goggles_tna_F",
		"G_RegulatorMask_F",
		"G_AirPurifyingRespirator_02_olive_F",
		"G_AirPurifyingRespirator_02_sand_F",
		"G_AirPurifyingRespirator_02_black_F",
		"G_WirelessEarpiece_F",
		"G_Lowprofile",
		"G_Shades_Black",
		"G_Shades_Blue",
	// ======================================================================
	//			SSU
	// ======================================================================
		// SSU Bandana ==================================================
			"G_SSU_Bandana_AOR1",
			"G_SSU_Bandana_AOR1_Beast",
			"G_SSU_Bandana_Sports_AOR1",
			"G_SSU_Bandana_Sports_AOR1_Beast",
			"G_SSU_Bandana_AOR2",
			"G_SSU_Bandana_AOR2_Beast",
			"G_SSU_Bandana_Sports_AOR2",
			"G_SSU_Bandana_Sports_AOR2_Beast",
			"G_SSU_Bandana_MCAM_Black",
			"G_SSU_Bandana_MCAM_Black_Beast",
			"G_SSU_Bandana_Sports_MCAM_Black",
			"G_SSU_Bandana_Sports_MCAM_Black_Beast",
			"G_SSU_Bandana_Black",
			"G_SSU_Bandana_Black_Beast",
			"G_SSU_Bandana_Sports_Black",
			"G_SSU_Bandana_Sports_Black_Beast",
			"G_SSU_Bandana_M81",
			"G_SSU_Bandana_M81_Beast",
			"G_SSU_Bandana_Sports_M81",
			"G_SSU_Bandana_Sports_M81_Beast",
			"G_SSU_Bandana_OCP",
			"G_SSU_Bandana_OCP_Beast",
			"G_SSU_Bandana_Sports_OCP",
			"G_SSU_Bandana_Sports_OCP_Beast",
			"G_SSU_Bandana_MCAM_Tropic",
			"G_SSU_Bandana_MCAM_Tropic_Beast",
			"G_SSU_Bandana_Sports_MCAM_Tropic",
			"G_SSU_Bandana_Sports_MCAM_Tropic_Beast",
			"G_SSU_Bandana_MCAM_Woodland",
			"G_SSU_Bandana_MCAM_Woodland_Beast",
			"G_SSU_Bandana_Sports_MCAM_Woodland",
			"G_SSU_Bandana_Sports_MCAM_Woodland_Beast",
		// SSU Balaclava ==================================================
			"G_SSU_Balaclava_TI_AOR1",
			"G_SSU_Balaclava_TI_G_AOR1",
			"G_SSU_Balaclava_TI_AOR2",
			"G_SSU_Balaclava_TI_G_AOR2",
			"G_SSU_Balaclava_TI_MCAM_Black",
			"G_SSU_Balaclava_TI_G_MCAM_Black",
			"G_SSU_Balaclava_TI_Black",
			"G_SSU_Balaclava_TI_G_Black",
			"G_SSU_Balaclava_TI_M81",
			"G_SSU_Balaclava_TI_G_M81",
			"G_SSU_Balaclava_TI_OCP",
			"G_SSU_Balaclava_TI_G_OCP",
			"G_SSU_Balaclava_TI_MCAM_Tropic",
			"G_SSU_Balaclava_TI_G_MCAM_Tropic",
			"G_SSU_Balaclava_TI_MCAM_Woodland",
			"G_SSU_Balaclava_TI_G_MCAM_Woodland"
];

_items = [
	// ======================================================================
	//		NVG
	// ======================================================================
		// CUP ==================================================
			"CUP_NVG_PVS15_black",
			"CUP_NVG_PVS15_green",
			"CUP_NVG_PVS15_Hide",
			"CUP_NVG_PVS15_tan",
			"CUP_NVG_PVS7",
			"CUP_NVG_PVS7_Hide",
			"CUP_NVG_PVS14",
			"CUP_NVG_PVS14_Hide",
			"CUP_NVG_GPNVG_black",
			"CUP_NVG_GPNVG_green",
			"CUP_NVG_GPNVG_Hide",
			"CUP_NVG_GPNVG_tan",
			"CUP_NVG_HMNVS",
			"CUP_NVG_HMNVS_Hide",
		// VANILA ==================================================
			"NVGoggles_INDEP",
			"NVGoggles",
			"NVGoggles_OPFOR",
			"O_NVGoggles_ghex_F",
			"NVGoggles_tna_F",
			"O_NVGoggles_grn_F",
	// ======================================================================
	//		Binoculars
	// ======================================================================
		// VANILA ==================================================
			"Binocular",
	// ======================================================================
	//		Map
	// ======================================================================
		// VANILA ==================================================
			"ItemMap",
	// ======================================================================
	//		Terminal
	// ======================================================================
		// VANILA ==================================================
			"ItemGPS",
	// ======================================================================
	//		Radio
	// ======================================================================
		// VANILA ==================================================
			"ItemRadio",
	// ======================================================================
	//		Compass
	// ======================================================================
		// VANILA ==================================================
			"ItemCompass",
	// ======================================================================
	//		Watch
	// ======================================================================
		// VANILA ==================================================
			"ItemWatch",
	// ======================================================================
	//		Other
	// ======================================================================
		// VANILA ==================================================
			"MineDetector",
			"FirstAidKit",
	// ======================================================================
	//		Grenades
	// ======================================================================
		// VANILA ==================================================
			"SmokeShell",
			"SmokeShellYellow",
			"SmokeShellGreen",
			"SmokeShellRed",
			"SmokeShellOrange",
			"SmokeShellPurple",
			"SmokeShellBlue",
			"O_IR_Grenade",
			"MiniGrenade",
			"HandGrenade",
			"Chemlight_yellow",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_blue",
		// CUP ==================================================
			"CUP_HandGrenade_M67",
			"CUP_HandGrenade_RGD5",
			"CUP_HandGrenade_RGO",
			"CUP_HandGrenade_L109A1_HE",
			"CUP_HandGrenade_L109A2_HE",
	// ======================================================================
	//		Mines
	// ======================================================================
		// VANILA ==================================================
			"DemoCharge_Remote_Mag",
			"SatchelCharge_Remote_Mag",
		// CUP ==================================================
			"CUP_PipeBomb_M",
			"CUP_TimeBomb_M"
];

_handgunWeapon = [
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP pistols ==================================================
			"CUP_hgun_Browning_HP",
			"CUP_hgun_CZ75",
			"CUP_hgun_Compact",
			"CUP_hgun_Duty",
			"CUP_hgun_Phantom",
			"CUP_hgun_Deagle",
			"CUP_hgun_Glock17",
			"CUP_hgun_Glock17_tan",
			"CUP_hgun_Glock17_blk",
			"CUP_hgun_M17_Black",
			"CUP_hgun_M17_Coyote",
			"CUP_hgun_M17_Green",
			"CUP_hgun_Colt1911",
			"hgun_esd_01_F",
			"CUP_hgun_M9",
			"CUP_hgun_M9A1",
			"CUP_hgun_Mk23",
			"CUP_hgun_TaurusTracker455",
			"CUP_hgun_TT",
			"CUP_hgun_PMM",
			"CUP_hgun_Makarov",
			"CUP_hgun_PB6P9",
		// CUP SMG ==================================================
			"CUP_hgun_Mac10",
			"CUP_hgun_MicroUzi",
			"CUP_hgun_MP7",
			"CUP_hgun_MP7_woodland",
			"CUP_hgun_MP7_desert",
			"CUP_hgun_SA61",
			"CUP_hgun_TEC9",
			"CUP_hgun_TEC9_FA",
	// ======================================================================
	//			VANILA
	// ======================================================================
	    "hgun_Pistol_heavy_01_F",
	    "hgun_ACPC2_F",
	    "hgun_P07_F",
	    "hgun_P07_khk_F",
		"hgun_P07_blk_F",
	    "hgun_Rook40_F",
	    "hgun_Pistol_heavy_02_F",
	    "hgun_Pistol_01_F",
	    "hgun_Pistol_heavy_01_green_F"
];

_secondaryWeapon = [];

_primaryWeapon = [
	// ======================================================================
	//			Vanilla
	// ======================================================================
		// VANILLA CTARS ==================================================
			"arifle_CTARS_blk_F",
			"arifle_CTARS_ghex_F",
			"arifle_CTARS_hex_F",
		// VANILLA XMS BASE ==============================================
			"arifle_XMS_M_lxWS",
			"arifle_XMS_M_Sand_lxWS",
			"arifle_XMS_M_khk_lxWS",
		// VANILLA MX SW ==================================================
			"arifle_MX_SW_Black_F",
			"arifle_MX_SW_khk_F",
		// VANILLA RPK12 ==================================================
			"arifle_RPK12_arid_F",
			"arifle_RPK12_F",
			"arifle_RPK12_lush_F",
		// VANILLA SDAR ==================================================
			"arifle_SDAR_F",
		// VANILLA SPAR 02 ==================================================
			"arifle_SPAR_02_blk_F",
			"arifle_SPAR_02_khk_F",
		// VANILLA LMG 03 ==================================================
			"LMG_03_F",
		// VANILLA Mk200 ==================================================
			"LMG_Mk200_F",
			"LMG_Mk200_black_F",
		// VANILLA Zafir ==================================================
			"LMG_Zafir_F",
		// VANILLA MMG 01 ==================================================
			"MMG_01_hex_F",
			"MMG_01_tan_F",
		// VANILLA MMG 02 ==================================================
			"MMG_02_black_F",
			"MMG_02_camo_F",
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP L86 A2 ==================================================
			"CUP_arifle_L86A2",
		// CUP MG36 ==================================================
			"CUP_arifle_MG36",
			"CUP_arifle_MG36_camo",
			"CUP_arifle_MG36_hex",
			"CUP_arifle_MG36_wdl",
		// CUP RPK74 ==================================================
			"CUP_arifle_RPK74",
			"CUP_arifle_RPK74_45",
			"CUP_arifle_RPK74_45_top_rail",
			"CUP_arifle_RPK74_top_rail",
		// CUP RPK74M ==================================================
			"CUP_arifle_RPK74M",
			"CUP_arifle_RPK74M_railed",
			"CUP_arifle_RPK74M_top_rail",
		// CUP XM8 ==================================================
			"CUP_arifle_xm8_SAW",
		// CUP FNMAG ==================================================
			"CUP_lmg_FNMAG",
			"CUP_lmg_FNMAG_RIS",
			"CUP_lmg_FNMAG_RIS_modern",
		// CUP L110 A1 ==================================================
			"CUP_lmg_L110A1",
		// CUP L7 A2 ==================================================
			"CUP_lmg_L7A2",
			"CUP_lmg_L7A2_Flat",
		// CUP M240 ==================================================
			"CUP_lmg_M240",
			"CUP_lmg_M240_B",
			"CUP_lmg_M240_norail",
		// CUP M249 ==================================================
			"CUP_lmg_M249_E1",
			"CUP_lmg_M249_E2",
			"CUP_lmg_m249_para",
			"CUP_lmg_m249_para_gl",
			"CUP_lmg_m249_pip1",
			"CUP_lmg_m249_pip2",
			"CUP_lmg_m249_pip3",
			"CUP_lmg_m249_pip4",
			"CUP_lmg_m249_SQuantoon",
		// CUP M60 ==================================================
			"CUP_lmg_M60",
		// CUP M60 E4 ==================================================
			"CUP_lmg_M60E4",
			"CUP_lmg_M60E4_desert",
			"CUP_lmg_M60E4_jungle",
			"CUP_lmg_M60E4_norail",
			"CUP_lmg_M60E4_norail_desert",
			"CUP_lmg_M60E4_norail_jungle",
			"CUP_lmg_M60E4_norail_wood",
			"CUP_lmg_M60E4_wood",
		// CUP MG3 ==================================================
			"CUP_lmg_MG3",
			"CUP_lmg_MG3_rail",
		// CUP minimi ==================================================
			"CUP_lmg_minimi",
			"CUP_lmg_minimi_railed",
			"CUP_lmg_minimipara",
		// CUP Mk48 ==================================================
			"CUP_lmg_Mk48",
			"CUP_lmg_Mk48_des",
			"CUP_lmg_Mk48_nohg",
			"CUP_lmg_Mk48_nohg_des",
			"CUP_lmg_Mk48_nohg_od",
			"CUP_lmg_Mk48_nohg_wdl",
			"CUP_lmg_Mk48_od",
			"CUP_lmg_Mk48_wdl",
		// CUP Pecheneg ==================================================
			"CUP_lmg_Pecheneg",
			"CUP_lmg_Pecheneg_B50_vfg",
			"CUP_lmg_Pecheneg_desert",
			"CUP_lmg_Pecheneg_top_rail",
			"CUP_lmg_Pecheneg_top_rail_B50_vfg",
			"CUP_lmg_Pecheneg_woodland",
		// CUP PKM ==================================================
			"CUP_lmg_PKM",
			"CUP_lmg_PKM_B50_vfg",
			"CUP_lmg_PKM_front_rail_B50_vfg",
			"CUP_lmg_PKM_top_rail",
			"CUP_lmg_PKM_top_rail_B50_vfg",
		// CUP PKMN ==================================================
			"CUP_lmg_PKMN",
		// CUP UK59 ==================================================
			"CUP_lmg_UK59"
];

_optics = [
	// ======================================================================
	//			VANILA
	// ======================================================================
		// VANILA ASSAULT RIFLES ==================================================
			"optic_aco",
			"optic_Aco",
			"optic_ACO_grn",
			"optic_ACO_grn_smg",
			"optic_aco_smg",
			"optic_Aco_smg",
			"optic_Arco",
			"optic_Arco_AK_arid_F",
			"optic_Arco_AK_blk_F",
			"optic_Arco_AK_lush_F",
			"optic_Arco_arid_F",
			"optic_Arco_blk_F",
			"optic_Arco_ghex_F",
			"optic_Arco_lush_F",
			"optic_ERCO_blk_F",
			"optic_ERCO_khk_F",
			"optic_Hamr",
			"optic_Hamr_khk_F",
			"optic_ico_01_black_f",
			"optic_ico_01_camo_f",
			"optic_ico_01_f",
			"optic_MRCO",
		// VANILA SNIPER RIFLES ==================================================
		// VANILA PISTOLS ==================================================
			"optic_Holosight",
			"optic_Holosight_arid_F",
			"optic_Holosight_blk_F",
			"optic_Holosight_khk_F",
			"optic_Holosight_lush_F",
			"optic_Holosight_smg",
			"optic_Holosight_smg_blk_F",
			"optic_Holosight_smg_khk_F",
			"optic_MRD",
			"optic_MRD_black",
			"optic_Yorris",
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP ASSAULT RIFLES ==================================================
			"CUP_optic_1p63",
			"CUP_optic_1P87_RIS",
			"CUP_optic_1P87_RIS_desert",
			"CUP_optic_1P87_RIS_woodland",
			"CUP_optic_AC11704_Black",
			"CUP_optic_AC11704_Coyote",
			"CUP_optic_AC11704_Jungle",
			"CUP_optic_AC11704_OD",
			"CUP_optic_ACOG",
			"CUP_optic_ACOG_Reflex_Desert",
			"CUP_optic_ACOG_Reflex_Wood",
			"CUP_optic_ACOG_TA01B_Black",
			"CUP_optic_ACOG_TA01B_Coyote",
			"CUP_optic_ACOG_TA01B_OD",
			"CUP_optic_ACOG_TA01B_RMR_Black",
			"CUP_optic_ACOG_TA01B_RMR_Coyote",
			"CUP_optic_ACOG_TA01B_RMR_OD",
			"CUP_optic_ACOG_TA01B_RMR_Tropic",
			"CUP_optic_ACOG_TA01B_Tropic",
			"CUP_optic_ACOG_TA01NSN_OD",
			"CUP_optic_ACOG_TA01NSN_RMR_Black",
			"CUP_optic_ACOG_TA01NSN_RMR_Coyote",
			"CUP_optic_ACOG_TA01NSN_RMR_OD",
			"CUP_optic_ACOG_TA01NSN_RMR_Tropic",
			"CUP_optic_ACOG_TA01NSN_Tropic",
			"CUP_optic_ACOG_TA31_KF",
			"CUP_optic_ACOG_TA31_KF_Desert",
			"CUP_optic_ACOG_TA31_KF_Wood",
			"CUP_optic_ACOG2",
			"CUP_optic_AIMM_COMPM2_BLK",
			"CUP_optic_AIMM_COMPM2_OD",
			"CUP_optic_AIMM_COMPM4_BLK",
			"CUP_optic_AIMM_M68_BLK",
			"CUP_optic_AIMM_M68_OD",
			"CUP_optic_AIMM_MARS_BLK",
			"CUP_optic_AIMM_MARS_OD",
			"CUP_optic_AIMM_MICROT1_BLK",
			"CUP_optic_AIMM_MICROT1_OD",
			"CUP_optic_AIMM_ZDDOT_BLK",
			"CUP_optic_Aimpoint_5000",
			"CUP_optic_AN_PVS_4_M16",
			"CUP_optic_CompM2_Black",
			"CUP_optic_CompM2_Coyote",
			"CUP_optic_CompM2_Desert",
			"CUP_optic_CompM2_low",
			"CUP_optic_CompM2_low_coyote",
			"CUP_optic_CompM2_low_OD",
			"CUP_optic_CompM2_OD",
			"CUP_optic_CompM2_Woodland",
			"CUP_optic_CompM2_Woodland2",
			"CUP_optic_CompM4",
			"CUP_optic_ekp_8_02",
			"CUP_optic_Elcan",
			"CUP_optic_Elcan_Coyote",
			"CUP_optic_Elcan_OD",
			"CUP_optic_Elcan_reflex",
			"CUP_optic_Elcan_reflex_Coyote",
			"CUP_optic_Elcan_reflex_OD",
			"CUP_optic_Elcan_SpecterDR",
			"CUP_optic_Elcan_SpecterDR_black",
			"CUP_optic_Elcan_SpecterDR_coyote",
			"CUP_optic_Elcan_SpecterDR_KF",
			"CUP_optic_Elcan_SpecterDR_KF_black",
			"CUP_optic_Elcan_SpecterDR_KF_coyote",
			"CUP_optic_Elcan_SpecterDR_KF_od",
			"CUP_optic_Elcan_SpecterDR_KF_RMR",
			"CUP_optic_Elcan_SpecterDR_KF_RMR_black",
			"CUP_optic_Elcan_SpecterDR_KF_RMR_coyote",
			"CUP_optic_Elcan_SpecterDR_KF_RMR_od",
			"CUP_optic_Elcan_SpecterDR_od",
			"CUP_optic_Elcan_SpecterDR_RMR",
			"CUP_optic_Elcan_SpecterDR_RMR_black",
			"CUP_optic_Elcan_SpecterDR_RMR_coyote",
			"CUP_optic_Elcan_SpecterDR_RMR_od",
			"CUP_optic_ElcanM145",
			"CUP_optic_Eotech533",
			"CUP_optic_Eotech533Grey",
			"CUP_optic_Eotech553_Black",
			"CUP_optic_Eotech553_Coyote",
			"CUP_optic_Eotech553_OD",
			"CUP_optic_G33_HWS_BLK",
			"CUP_optic_G33_HWS_COYOTE",
			"CUP_optic_G33_HWS_OD",
			"CUP_optic_G36DualOptics",
			"CUP_optic_G36DualOptics_3D",
			"CUP_optic_G36DualOptics_desert",
			"CUP_optic_G36DualOptics_desert_3D",
			"CUP_optic_G36DualOptics_wood",
			"CUP_optic_G36DualOptics_wood_3D",
			"CUP_optic_G36Optics",
			"CUP_optic_G36Optics_3D",
			"CUP_optic_G36Optics_desert",
			"CUP_optic_G36Optics_desert_3D",
			"CUP_optic_G36Optics_Holo",
			"CUP_optic_G36Optics_Holo_3D",
			"CUP_optic_G36Optics_Holo_desert",
			"CUP_optic_G36Optics_Holo_desert_3D",
			"CUP_optic_G36Optics_Holo_wood",
			"CUP_optic_G36Optics_Holo_wood_3D",
			"CUP_optic_G36Optics_RDS",
			"CUP_optic_G36Optics_RDS_3D",
			"CUP_optic_G36Optics_RDS_desert",
			"CUP_optic_G36Optics_RDS_desert_3D",
			"CUP_optic_G36Optics_RDS_wood",
			"CUP_optic_G36Optics_RDS_wood_3D",
			"CUP_optic_G36Optics_wood",
			"CUP_optic_G36Optics_wood_3D",
			"CUP_optic_G36Optics15x",
			"CUP_optic_G36Optics15x_3D",
			"CUP_optic_G36Optics15x_desert",
			"CUP_optic_G36Optics15x_desert_3D",
			"CUP_optic_G36Optics15x_wood",
			"CUP_optic_G36Optics15x_wood_3D",
			"CUP_optic_HensoldtZO",
			"CUP_optic_HensoldtZO_coyote",
			"CUP_optic_HensoldtZO_desert",
			"CUP_optic_HensoldtZO_hex",
			"CUP_optic_HensoldtZO_low",
			"CUP_optic_HensoldtZO_low_coyote",
			"CUP_optic_HensoldtZO_low_desert",
			"CUP_optic_HensoldtZO_low_hex",
			"CUP_optic_HensoldtZO_low_od",
			"CUP_optic_HensoldtZO_low_RDS",
			"CUP_optic_HensoldtZO_low_RDS_coyote",
			"CUP_optic_HensoldtZO_low_RDS_desert",
			"CUP_optic_HensoldtZO_low_RDS_hex",
			"CUP_optic_HensoldtZO_low_RDS_od",
			"CUP_optic_HensoldtZO_od",
			"CUP_optic_HensoldtZO_RDS",
			"CUP_optic_HensoldtZO_RDS_coyote",
			"CUP_optic_HensoldtZO_RDS_desert",
			"CUP_optic_HensoldtZO_RDS_hex",
			"CUP_optic_HensoldtZO_RDS_od",
			"CUP_optic_HoloBlack",
			"CUP_optic_HoloDesert",
			"CUP_optic_HoloWdl",
			"CUP_optic_Kobra",
			"CUP_optic_LeupoldMk4_CQ_T",
			"CUP_optic_MARS",
			"CUP_optic_MARS_OD",
			"CUP_optic_MEPRO",
			"CUP_optic_MEPRO_moa_clear",
			"CUP_optic_MEPRO_openx_orange",
			"CUP_optic_MEPRO_tri_clear",
			"CUP_optic_MicroT1",
			"CUP_optic_MicroT1_coyote",
			"CUP_optic_MicroT1_low",
			"CUP_optic_MicroT1_low_coyote",
			"CUP_optic_MicroT1_low_OD",
			"CUP_optic_MicroT1_OD",
			"CUP_optic_MRad",
			"CUP_optic_NSPU",
			"CUP_optic_PechenegScope",
			"CUP_optic_PEM",
			"CUP_optic_PSO_1",
			"CUP_optic_PSO_1_1",
			"CUP_optic_PSO_1_1_open",
			"CUP_optic_PSO_1_AK",
			"CUP_optic_PSO_1_AK_open",
			"CUP_optic_PSO_1_open",
			"CUP_optic_RCO",
			"CUP_optic_RCO_desert",
			"CUP_optic_Remington",
			"CUP_optic_SB_11_4x20_PM",
			"CUP_optic_SB_11_4x20_PM_od",
			"CUP_optic_SUSAT",
			"CUP_optic_TrijiconRx01_black",
			"CUP_optic_TrijiconRx01_desert",
			"CUP_optic_TrijiconRx01_kf_black",
			"CUP_optic_TrijiconRx01_kf_desert",
			"CUP_optic_TrijiconRx01_kf_od",
			"CUP_optic_TrijiconRx01_od",
			"CUP_optic_VortexRazor_UH1_Black",
			"CUP_optic_VortexRazor_UH1_Coyote",
			"CUP_optic_VortexRazor_UH1_Khaki",
			"CUP_optic_VortexRazor_UH1_OD",
			"CUP_optic_ZDDot",
			"CUP_optic_ZeissZPoint",
			"CUP_optic_ZeissZPoint_hex",
			"CUP_optic_ZeissZPoint_wood",
			"CUP_optic_OCP_7",
			"CUP_optic_OCP_7_w",
			"CUP_optic_OCP_7_d",
			"CUP_optic_OCP_7_rail",
			"CUP_optic_OCP_7_w_rail",
			"CUP_optic_OCP_7_d_rail"
];

_muzzles = [
	// ======================================================================
	//			VANILA
	// ======================================================================
		// VANILA muzzle for pistols ==================================================
			"muzzle_snds_acp",
			"muzzle_snds_L",
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP muzzle for pistols ==================================================
			"CUP_muzzle_snds_mk23",
			"CUP_muzzle_snds_M9"
];

_pointers = [
	// ======================================================================
	//			VANILA
	// ======================================================================
		// VANILA acc for pistols ==================================================
			"acc_flashlight_pistol",
		// VANILA acc for rifles ==================================================
			"acc_flashlight",
			"acc_flashlight_smg_01",
			"acc_pointer_IR",
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP acc for pistols ==================================================
			"CUP_acc_MLPLS_Laser",
			"CUP_acc_Glock17_Flashlight",
			"CUP_acc_CZ_M3X",
		// CUP acc for rifles ==================================================
			"CUP_acc_ANPEQ_15",
			"CUP_acc_ANPEQ_15_Black",
			"CUP_acc_ANPEQ_15_Black_Top",
			"CUP_acc_ANPEQ_15_Flashlight_Black_F",
			"CUP_acc_ANPEQ_15_Flashlight_Black_L",
			"CUP_acc_ANPEQ_15_Flashlight_OD_F",
			"CUP_acc_ANPEQ_15_Flashlight_OD_L",
			"CUP_acc_ANPEQ_15_Flashlight_Tan_F",
			"CUP_acc_ANPEQ_15_Flashlight_Tan_L",
			"CUP_acc_ANPEQ_15_OD",
			"CUP_acc_ANPEQ_15_OD_Top",
			"CUP_acc_ANPEQ_15_Tan_Top",
			"CUP_acc_ANPEQ_15_Top_Flashlight_Black_F",
			"CUP_acc_ANPEQ_15_Top_Flashlight_Black_L",
			"CUP_acc_ANPEQ_15_Top_Flashlight_OD_F",
			"CUP_acc_ANPEQ_15_Top_Flashlight_OD_L",
			"CUP_acc_ANPEQ_15_Top_Flashlight_Tan_F",
			"CUP_acc_ANPEQ_15_Top_Flashlight_Tan_L",
			"CUP_acc_ANPEQ_2",
			"CUP_acc_ANPEQ_2_Black_Top",
			"CUP_acc_ANPEQ_2_camo",
			"CUP_acc_ANPEQ_2_Coyote_Top",
			"CUP_acc_ANPEQ_2_desert",
			"CUP_acc_ANPEQ_2_Flashlight_Black_F",
			"CUP_acc_ANPEQ_2_Flashlight_Black_L",
			"CUP_acc_ANPEQ_2_Flashlight_Coyote_F",
			"CUP_acc_ANPEQ_2_Flashlight_Coyote_L",
			"CUP_acc_ANPEQ_2_Flashlight_OD_F",
			"CUP_acc_ANPEQ_2_Flashlight_OD_L",
			"CUP_acc_ANPEQ_2_grey",
			"CUP_acc_ANPEQ_2_OD_Top",
			"CUP_acc_CZ_M3X_L",
			"CUP_acc_Flashlight",
			"CUP_acc_Flashlight_desert",
			"CUP_acc_Flashlight_wdl",
			"CUP_acc_LLM",
			"CUP_acc_LLM_black",
			"CUP_acc_LLM_Flashlight",
			"CUP_acc_LLM_od",
			"CUP_acc_LLM01_coyote_L",
			"CUP_acc_LLM01_desert_L",
			"CUP_acc_LLM01_hex_L",
			"CUP_acc_LLM01_L",
			"CUP_acc_LLM01_od_L",
			"CUP_acc_sffh",
			"CUP_acc_XM8_light_module",
			"CUP_SVD_camo_g",
			"CUP_SVD_camo_d"
];

_bipods = [
	// ======================================================================
	//			VANILA
	// ======================================================================
		"bipod_01_F_blk",
		"bipod_01_F_khk",
		"bipod_01_F_mtp",
		"bipod_02_F_arid",
		"bipod_02_F_blk",
		"bipod_02_F_hex",
		"bipod_02_F_lush",
		"bipod_02_F_tan",
		"bipod_03_F_blk",
		"bipod_03_F_oli",
	// ======================================================================
	//			CUP
	// ======================================================================
		"CUP_bipod_FNFAL",
		"CUP_bipod_G3",
		"CUP_Bipod_G36",
		"CUP_Bipod_G36_desert",
		"CUP_Bipod_G36_wood",
		"CUP_bipod_G3SG1",
		"CUP_bipod_Harris_1A2_L",
		"CUP_bipod_Harris_1A2_L_BLK",
		"CUP_bipod_VLTOR_Modpod",
		"CUP_bipod_VLTOR_Modpod_black",
		"CUP_bipod_VLTOR_Modpod_od"
];

_exclMag = [
	// ======================================================================
	//			VANILA
	// ======================================================================
		"APERSBoundingMine_Range_Mag",
		"APERSMine_Range_Mag",
		"APERSMineDispenser_Mag",
		"APERSTripMine_Wire_Mag",
		"ATMine_Range_Mag",
		"ClaymoreDirectionalMine_Remote_Mag",
		"IEDLandSmall_Remote_Mag",
		"IEDUrbanSmall_Remote_Mag",
		"SLAMDirectionalMine_Wire_Mag",
		"TrainingMine_Mag",
	// ======================================================================
	//			CUP
	// ======================================================================
		"CUP_12Rnd_B_Saiga12_HE",
		"CUP_1Rnd_12Gauge_HE",
		"CUP_20Rnd_B_AA12_HE",
		"CUP_5Rnd_B_Saiga12_HE",
		"CUP_6Rnd_12Gauge_HE",
		"CUP_8Rnd_12Gauge_HE",
		"CUP_8Rnd_12Gauge_HE",
		"CUP_IED_V1_M",
		"CUP_IED_V2_M",
		"CUP_IED_V3_M",
		"CUP_IED_V4_M",
		"CUP_Mine_M",
		"CUP_MineE_M"
];

_allowedRockets = [
	// ======================================================================
	//			VANILA
	// ======================================================================
		"MRAWS_HE_F",
		"MRAWS_HEAT_F",
		"MRAWS_HEAT55_F",
		"NLAW_F",
		"RPG32_F",
		"RPG32_HE_F",
		"RPG7_F",
		"SPG9_HE",
		"SPG9_HEAT",
		"Titan_AA",
		"Titan_AP",
		"Titan_AT",
		"Vorona_HE",
		"Vorona_HEAT",
	// ======================================================================
	//			CUP
	// ======================================================================
		"CUP_AT13_M",
		"CUP_Dragon_EP1_M",
		"CUP_Igla_M",
		"CUP_Javelin_M",
		"CUP_M136_M",
		"CUP_M72A6_M",
		"CUP_MAAWS_HEAT_M",
		"CUP_MAAWS_HEAT_M",
		"CUP_MAAWS_HEDP_M",
		"CUP_NLAW_M",
		"CUP_OG7_M",
		"CUP_PG7V_M",
		"CUP_PG7VL_M",
		"CUP_PG7VM_M",
		"CUP_PG7VR_M",
		"CUP_RPG18_M",
		"CUP_SMAW_HEAA_M",
		"CUP_SMAW_HEDP_M",
		"CUP_SMAW_NE_M",
		"CUP_SMAW_Spotting",
		"CUP_Stinger_M",
		"CUP_Strela_2_M",
		"CUP_TBG7V_M"
];

_exclTypes = [];

_magazins = [];

{
    if (getNumber (_x >> "scope") == 2 || getNumber (_x >> "scopeArsenal") == 2) then {
        private _nameSound = getText (_x >> "nameSound");
        if !(_nameSound in _exclTypes) then {
            _magazins pushBack (configname _x);
        } else {
            if ((configname _x) in _allowedRockets) then {
                _magazins pushBack (configname _x);
            };
        };
    };
} forEach ("true" configclasses (configfile >> "CfgMagazines"));

_magazines = _magazins - _exclMag;